import {cityDistricts,cityDistrictLinks} from './eldervale-city-data.mjs';

const art='/art/maps/eldervale-city-v1.png';
const neighbourStories={
 lantern:'“My grandmother lit these lanes before the blue glass arrived. People still put a candle out for a neighbour coming home late; enchantment never replaced that.”',
 delvers:'“I keep the return column wider than the departure column. A crew is not a number, and a good expedition ends upstairs with everybody at the table.”',
 crown:'“A petition can come in flour-stained paper or gilt parchment. I put both in the same register. If somebody tells you otherwise, send them to my desk.”',
 old:'“This lintel belonged to a bakery before it belonged to a shrine. Cities keep borrowing each other’s stones. The trouble starts when they forget whose names were carved on them.”',
 exchange:'“My first stall sold six jars of saffron and one very convincing empty jar. That was when I learned to check a promise by weight, not volume.”',
 quays:'“A tide ledger is a conversation with yesterday. People ask me whether the river is enchanted. I say it is difficult enough without giving it ideas.”',
 forge:'“Clockwork is not silent magic. It complains, collects dust and needs somebody patient to listen. I like that about it.”',
 scholars:'“I failed my first demonstration in front of forty students. The measuring charm was sound; I had measured the wrong bridge. Precision is not the same as understanding.”',
 temples:'“Some people come here to pray. Others need somewhere to sit without buying anything. Both deserve a chair.”',
 mourning:'“The gardens are for living visitors as well as those we remember. Children bring daisies, gardeners argue over yews, and nobody has to whisper merely because grief lives here.”',
 lowwater:'“The city calls this Lowwater as if height were character. We keep the warning flags ready and the neighbours informed. That is worth more than a dry pair of expensive shoes.”',
 greenwall:'“The orchard committee once debated a pear for an entire afternoon. It was a very good pear. We made the decision before anybody could enchant it into a witness.”',
};
const districtId=id=>'city-'+id;
const placeId=(district,key)=>districtId(district)+'-'+key;
const positions=[[20,20],[50,16],[80,20],[84,50],[80,80],[50,84],[20,80],[16,50]];
const flags={cityDescentBriefed:false,cityCryptBriefed:false,cityPumpBriefed:false,citySealCopied:false,citySealReported:false,cityGateAligned:false,cityGateAdvice:false,citySentinelResolved:false};
const set=(name)=>({op:'set',path:'flags.'+name,value:true});
const flag=name=>({path:'flags.'+name,equals:true});
const action=(id,location,verbs,targets,effects,message,extra={})=>({id,location,modes:['act'],verbs,targets,effects,outcome:{message},...extra});
const jobs={lantern:['lamps','fasten','loose lamp shutter','The shutter is fastened. Blue light now falls steadily across the yard.'],crown:['petition','record','public petition register','Your volunteered concern is recorded in the public register; no audience or official favour is awarded.'],exchange:['scales','balance','marked weights','The marked demonstration weights balance correctly; the market steward thanks the company.'],quays:['bell','free','snagged bell rope','The snagged rope is freed and the quay warning bell rings clearly.'],forge:['shutter','secure','cold forge hinge','The cold forge hinge is secured safely; no hot machinery is operated.'],scholars:['library','sort','catalogue cards','The catalogue cards are sorted and the public reading desk is usable again.'],temples:['ribbons','tie','memorial ribbons','The offered memorial ribbons are tied neatly; the quiet ceremony continues.'],mourning:['tools','raise','fallen path sign','The fallen path sign is raised. Visitors can find the maintained memorial walk.'],lowwater:['pennant','fasten','warning pennant','The warning pennant is fastened above the floodline. Neighbours can see the public signal.'],greenwall:['festival','untangle','festival ribbons','The festival ribbons are untangled and the public pavilion is ready for its gathering.']};

export const cityAtlases=cityDistricts.map(d=>{
  const root=districtId(d.id),places=[{id:root,name:d.name,x:50,y:50},...d.places.map((p,i)=>({id:placeId(d.id,p[0]),name:p[1],x:positions[i][0],y:positions[i][1]}))];
  const links=d.places.map((p,i)=>[placeId(d.id,p[0]),placeId(d.id,d.places[(i+1)%8][0])]);
  for(const i of [0,2,4,6])links.push([root,places[i+1].id]);
  return {id:root,title:d.name,root:'city',image:art,imageAlt:'Illustrated Eldervale city, focused on '+d.name,imageViewport:{x:d.x,y:d.y,scale:2.4},introduction:d.mood,returnHint:'Return to the district junction for neighbouring districts. Eldervale Waygate connects the public roads and your paused main adventure.',places,links,actionIds:[...(jobs[d.id]?[root+'-help']:[]),...(d.id==='delvers'?['city-report-seal','city-delvers-last-brief','city-delvers-maps-brief']:[]),...(d.id==='mourning'?['city-mourning-crypt-brief']:[]),...(d.id==='lowwater'?['city-lowwater-pump-brief']:[])],taskStages:[...(jobs[d.id]?[{requires:[flag('cityHelp'+d.id)],text:jobs[d.id][3]+' Your help is remembered. Explore further or return to your main adventure.'}]:[]),{requires:[],text:'Meet the district resident, inspect the public directory and explore the connected streets. Local help is optional; shops do not yet sell equipment.'}]};
});
export const cityOverview={id:'eldervale-city',title:'Eldervale · Twelve districts',root:'city',image:art,imageAlt:'Detailed illustrated walled river city of Eldervale',introduction:'A living city above buried cities. Public districts are charted; discoveries and underground rooms are revealed only through exploration.',returnHint:'Travel follows connected streets, not remote map clicks. The Last Lantern is the delvers’ tavern; the Crooked Lantern remains your neighbourhood inn.',places:[{id:'city',name:'Eldervale Waygate',x:9,y:84},...cityDistricts.map(d=>({id:districtId(d.id),name:d.name,x:d.x,y:d.y}))],links:[...['lantern','delvers','greenwall'].map(id=>['city',districtId(id)]),...cityDistrictLinks.map(([a,b])=>[districtId(a),districtId(b)])],actionIds:[],taskStages:[{requires:[],text:'Twelve districts, ninety-six public destinations, twelve resident guides and an upper buried-city expedition. Start at a district junction, then explore its local streets.'}]};

const rooms=[
 ['landing','Rope Landing','Lantern light falls from the Last Lantern shaft onto a railed landing. A return stair remains open.','return stair','The maintained stair leads back to the Last Lantern.'],
 ['steps','Pilgrims’ Steps','Worn stairs meet the cemetery catacomb entrance. Names are carved into the handrail.','memorial handrail','The names are public memorials, not hidden campaign identities.'],
 ['cistern','Upper Cistern','Water glimmers behind a guarded sluice beneath Lowwater. A maintained inspection stair leads up.','water gauge','The gauge is sound. No flooding or resource change occurs by looking.'],
 ['crossing','Buried Crossing','Three old streets converge beneath faded municipal signs.','old street signs','The signs mark the landing, memorial walk and cistern; all return routes stay open.'],
 ['plaza','Seal Plaza','A municipal seal survives in a dry public square beneath the newer city.','municipal seal','A rubbing can be made here using the fixed survey board; the seal stays in place.'],
 ['gallery','Echo Gallery','A long gallery carries sound between cracked stone arches.','echo arches','The gallery connects the plaza to a side circuit; it does not summon unseen creatures.'],
 ['refuge','Surveyors’ Refuge','A sheltered alcove holds an emergency route chart and an empty bench.','return route chart','The chart independently explains the gate alignment: turn its marked wheel until the two bronze arrows meet.'],
 ['ward','Ward Street','An ink-dark sentinel stirs above a broken ward line. The side gallery offers another route.','broken ward line','The sentinel guards this optional street. Going around through the gallery avoids it.'],
 ['wheel','Gatehouse Workshop','Two bronze arrows flank a clearly marked control wheel.','gate instructions','The surviving instructions say to turn the marked wheel until the two bronze arrows meet. Inspection does not turn it.'],
 ['gate','Municipal Gate','A counterbalanced gate blocks the deeper public archive until its arrows are aligned.','gate arrows','The two arrows indicate the workshop wheel position. The gate only opens after deliberately operating the wheel.'],
 ['archive','First-City Archive','Stone shelves preserve a public index of the buried city’s successive rebuildings.','rebuilding index','The first city was rebuilt over, not erased. Further depths are not yet open for play.'],
 ['boundary','Citadel Threshold','An immense sealed bronze portal bears the emblem of the buried citadel.','sealed citadel portal','This is the boundary of the currently authored expedition. The lower citadel is future content; no generated passage continues beyond it.'],
];
const undergroundLinks=[['landing','crossing'],['steps','crossing'],['cistern','crossing'],['crossing','plaza'],['plaza','gallery'],['gallery','refuge'],['refuge','wheel'],['plaza','ward'],['ward','wheel'],['wheel','gate'],['gate','archive'],['archive','boundary'],['refuge','cistern']];
const underId=id=>'city-under-'+id;
const pastimes=[
 ['city-lantern-court','set','neighbour chessboard','The company sets the demonstration knight on the marked square. A neighbour explains the study; the board and pieces stay in the court.'],
 ['city-lantern-stage','unfold','paper dragon','The paper dragon spreads its wings above the rehearsal stand. Children applaud the small performance; no spell or combat ability is gained.'],
 ['city-delvers-rope','tie','practice rope','The company ties and checks the demonstration bowline over the padded pit. Hester’s practice line stays here; no equipment is taken.'],
 ['city-exchange-fabric','secure','banner clip','The demonstration banner is secured to its fixed display clip. Stallholders cheer the recovered colour; no cloth enters your inventory.'],
 ['city-scholars-garden','join','public debate','The company joins a public debate about measuring enchanted bridges. The discussion is recorded as a local visit, not a spell lesson or a promised quest.'],
 ];
for(const [location] of pastimes)cityAtlases.find(a=>a.places.some(p=>p.id===location)).actionIds.push(location+'-pastime');
export const undercityAtlas={id:'city-undercity',title:'The Buried City · Upper Survey',root:'city',image:art,imageAlt:'Revealed underground survey of Eldervale',schematic:true,introduction:'A fixed, persistent first expedition with three surface approaches, a side circuit and safe backtracking. Only revealed rooms are shown.',returnHint:'The landing returns to the Last Lantern; the steps to Mourning Gardens; the cistern to Lowwater. Deeper citadel content is not yet open.',places:rooms.map((r,i)=>({id:underId(r[0]),name:r[1],x:18+(i%3)*31,y:12+Math.floor(i/3)*23})),links:undergroundLinks.map(([a,b])=>[underId(a),underId(b)]),actionIds:['city-copy-seal','city-align-gate','city-gate-advice-refuge','city-gate-advice-wheel'],taskStages:[{requires:[flag('citySealReported')],text:'Hester has recorded your seal rubbing. The survey and its return routes remain open.'},{requires:[flag('citySealCopied')],text:'Return to Hester in Delvers’ Quarter and report the municipal seal.'},{requires:[],text:'Survey the upper buried city, copy the municipal seal at Seal Plaza and return safely. The sentinel street is optional; the gallery is an alternative route.'}]};

export function withEldervaleCity(base){
 const locations={...base.locations},npcs={...base.story.npcs},interactions=[...base.interactions],initialFlags={...base.initialFlags,...flags};
 for(const [location,verb,target,message] of pastimes){const name='cityPastime'+location;initialFlags[name]=false;interactions.push(action(location+'-pastime',location,[verb],[target],[set(name)],message,{repeat:{message:'This visit is already remembered. '+message}}));}
 locations.city={...locations.city,description:'At Eldervale Waygate, public roads enter a vast city of twelve districts. District signs point to Lantern Ward, Delvers’ Quarter and Greenwall. Sable tends the waygate; the Crooked Lantern is an inn within Lantern Ward.',exits:[...locations.city.exits,...cityOverview.links.filter(l=>l[0]==='city').map(l=>({to:l[1],via:'city street to '+cityDistricts.find(d=>districtId(d.id)===l[1]).name}))]};
 for(const [index,d] of cityDistricts.entries()){
  const atlas=cityAtlases[index],root=districtId(d.id),npc=root+'-resident',job=jobs[d.id],jobFlag='cityHelp'+d.id;
  if(job)initialFlags[jobFlag]=false;
  const directory=d.places.map(p=>p[1]).join('; ');
  npcs[npc]={name:d.resident.name,role:d.resident.species+' '+d.resident.role,locations:[root],goals:['Care for the district','Give truthful public directions'],knows:[d.mood,directory],voice:d.resident.voice,mustNotKnow:['Hidden main-campaign answers','Unvisited private events'],conversation:{publicFacts:[d.resident.appearance,d.mood,'Public places in this district: '+directory,'The local association is '+d.faction+'. Visiting does not grant membership.',...(d.id==='delvers'?['Read the Last Lantern safety ledger or the public survey folio, descend to Seal Plaza, copy its municipal seal and report back to me.']:[])],conditionalFacts:job?[{requires:[{path:'flags.'+jobFlag,equals:false}],fact:'If you would like to help, '+job[1]+' the '+job[2]+' at '+d.places.find(p=>p[0]===job[0])[1]+'.'},{requires:[flag(jobFlag)],fact:job[3]}]:[]}};
  npcs[npc].conversation.publicFacts.push(neighbourStories[d.id]);
  if(d.id==='delvers'){npcs[npc].conversation.publicFacts=npcs[npc].conversation.publicFacts.filter(f=>!f.startsWith('Read the Last Lantern'));npcs[npc].conversation.conditionalFacts.push({requires:[{path:'flags.citySealReported',equals:false}],fact:'Read the Last Lantern safety ledger or public survey folio. Copy the municipal seal at Seal Plaza and report back to me; the gallery bypasses the sentinel street.'},{requires:[flag('citySealReported')],fact:'“Your municipal seal record is in the register. The upper survey remains open, but the deeper citadel is still sealed. Thank you for coming back safely.”'});}
  for(const [i,p] of atlas.places.entries()){
   const row=i?d.places[i-1]:null,edges=atlas.links.filter(l=>l.includes(p.id)).map(l=>({to:l.find(id=>id!==p.id),via:'public lane to '+atlas.places.find(q=>q.id===l.find(id=>id!==p.id)).name}));
   if(!i)edges.push(...cityOverview.links.filter(l=>l.includes(root)).map(l=>{const to=l.find(id=>id!==root);return {to,via:'city street to '+(to==='city'?'Eldervale Waygate':cityDistricts.find(q=>districtId(q.id)===to).name)};}));
   locations[p.id]={name:p.name,description:row?row[2]:d.mood+' Public signs list: '+directory+'.',stage:0,aliases:[p.name],map:{x:1000+index*300+(i%3)*80,y:1000+Math.floor(i/3)*65,w:65,h:50,kind:'court',label:p.name},features:row?[{id:p.id+'-feature',label:row[3],kind:'scenery',observation:row[4]}]:[{id:npc,label:d.resident.name,kind:'npc'},{id:root+'-directory',label:'district directory',kind:'scenery',observation:directory}],occupants:i?['local people going about their day']:['neighbours and visitors at the district junction'],ambientGreeting:'A neighbour returns the greeting and gestures toward the district signs.',exits:edges,entryBeats:i?[]:[{id:npc+'-welcome',npc,text:d.resident.greeting}]};
  }
if(job){const location=placeId(d.id,job[0]),id=root+'-help';interactions.push(action(id,location,[job[1],'help','fix'],[job[2]],[set(jobFlag)],job[3],{repeat:{message:job[3]+' Your help is already remembered; no duplicate reward is given.'}}));locations[location].presentations=[{requires:[flag(jobFlag)],description:locations[location].name+'. '+job[3]}];locations[location].features[0]={...locations[location].features[0],presentations:[{requires:[flag(jobFlag)],observation:job[3]}]};}
 }
 for(const [location,target,name] of [['city-delvers-last','descent safety ledger','cityDescentBriefed'],['city-delvers-maps','public survey folio','cityDescentBriefed'],['city-mourning-crypt','public crypt register','cityCryptBriefed'],['city-lowwater-pump','pumping station notice','cityPumpBriefed']])interactions.push(action(location+'-brief',location,['read','study'],[target],[set(name)],'The maintained upper-city approach and its return route are recorded. You may now deliberately enter; reading does not move the company.'));
 for(const [i,r] of rooms.entries())locations[underId(r[0])]={name:r[1],description:r[2],stage:0,aliases:[r[1]],map:{x:1000+(i%3)*85,y:1400+Math.floor(i/3)*65,w:70,h:50,kind:'passage',label:r[1]},features:[{id:underId(r[0])+'-feature',label:r[3],kind:'scenery',observation:r[4]}],exits:undergroundLinks.filter(l=>l.includes(r[0])).map(l=>{const to=l.find(id=>id!==r[0]);return {to:underId(to),via:'buried street to '+rooms.find(q=>q[0]===to)[1],...((r[0]==='gate'&&to==='archive')||(r[0]==='archive'&&to==='gate')?{requires:[flag('cityGateAligned')]}:{})};})};
 for(const [surface,room,requirement] of [['city-delvers-last','landing','cityDescentBriefed'],['city-mourning-crypt','steps','cityCryptBriefed'],['city-lowwater-pump','cistern','cityPumpBriefed']]){locations[surface].exits.push({to:underId(room),via:'maintained descent to '+locations[underId(room)].name,requires:[flag(requirement)]});locations[underId(room)].exits.push({to:surface,via:'return stair to '+locations[surface].name});}
 npcs['city-last-host']={name:'Selka Emberglass',role:'Tiefling Last Lantern host',locations:['city-delvers-last'],voice:'Warm, wry and fiercely protective of returning crews.',goals:['Welcome returning expeditions','Keep the public shaft safe'],knows:['The Last Lantern is the central expedition tavern.','Hester records the upper municipal-seal survey at the district junction.'],mustNotKnow:['Private campaign discoveries','Future undercity depths'],conversation:{publicFacts:['Selka is a tiefling woman with curved charcoal horns, an embroidered apron and a laugh like a struck glass.','“Our tables are scarred because people come back with stories. I prefer that to pristine furniture and empty chairs.”','“The Last Lantern is this tavern. The Crooked Lantern is a neighbourhood inn in Lantern Ward; the two have different doors and different stories.”','Hester records the municipal-seal survey at the Delvers’ Quarter junction.'],conditionalFacts:[{requires:[{path:'flags.cityDescentBriefed',equals:false}],fact:'Read our descent safety ledger or the public survey folio at Moth & Compass Maps before using the maintained descent.'},{requires:[flag('cityDescentBriefed')],fact:'Your briefing is recorded. The maintained descent reaches Rope Landing; its return stair remains open.'}]}};
 locations['city-delvers-last'].features.push({id:'city-last-host',label:'Selka Emberglass',kind:'npc'});locations['city-delvers-last'].entryBeats=[{id:'city-last-host-welcome',npc:'city-last-host',text:'Selka slides a clean empty glass across the bar. “Welcome to the Last Lantern. Read the safety ledger before taking our descent; I like to know my guests have a way back.”'}];
 locations[underId('gate')].presentations=[{requires:[flag('cityGateAligned')],description:'The municipal gate stands open with its bronze arrows aligned. The archive and return street remain connected.'}];
 locations[underId('gate')].features[0].presentations=[{requires:[flag('cityGateAligned')],observation:'The arrows are aligned and the gate remains open.'}];
 locations[underId('ward')].presentations=[{requires:[flag('citySentinelResolved')],description:'The broken ward line is quiet. The defeated sentinel does not return; Ward Street remains safe.'}];
 for(const [key,name,role,description,greeting] of [['refuge','Bora Flintwake','Dwarf survey keeper','A dwarf woman in a patched survey coat, keeping the refuge chart legible.','“Keep your return route,” Bora says. “The gallery goes around Ward Street. The chart explains the municipal gate.”'],['cistern','Arven Reed','Orc inspection keeper','An orc man with a brass gauge and a dry inspection ledger.','Arven checks the water line. “The maintained stair reaches Lowwater. No swimming, no improvised tunnels; use the marked streets.”']]){
  const id=underId(key)+'-keeper',location=underId(key);
  npcs[id]={name,role,locations:[location],voice:'Calm, observant and respectful of safe exploration.',goals:['Maintain the upper survey','Help visitors return safely'],knows:[description,greeting],mustNotKnow:['Future depths','Hidden main-campaign answers'],conversation:{publicFacts:[description,greeting,'The Last Lantern landing, Mourning Gardens steps and Lowwater cistern are the three maintained approaches.','The lower citadel is sealed and is not currently open for expeditions.']}};
  locations[location].features.push({id,label:name,kind:'npc'});locations[location].entryBeats=[{id:id+'-welcome',npc:id,text:greeting}];
 }
 for(const room of ['refuge','wheel'])interactions.push(action('city-gate-advice-'+room,underId(room),['read','study'],[room==='refuge'?'return route chart':'gate instructions'],[set('cityGateAdvice')],'The instructions establish the safe operation: deliberately turn the marked workshop wheel until the bronze arrows meet. Reading moves nothing.'));
 interactions.push(action('city-copy-seal',underId('plaza'),['copy','rub','record'],['municipal seal'],[set('citySealCopied')],'The company makes a record at the fixed survey board. The municipal seal remains intact; return to Hester with the knowledge.'),action('city-align-gate',underId('wheel'),['turn','align','operate'],['marked wheel','control wheel'],[set('cityGateAligned')],'The bronze arrows align and the municipal gate opens. It remains open for backtracking.',{requires:[flag('cityGateAdvice')],blocked:{message:'Read the workshop gate instructions or the refuge route chart before operating the mechanism.'}}),{...action('city-report-seal','city-delvers',['report','tell','share'],['municipal seal','seal rubbing'],[set('citySealReported')],'Hester records the seal and your safe return. “A city remembering itself. That is worth more than a stolen relic.” The optional survey is complete; no campaign levels are granted.'),modes:['act','speak'],requires:[flag('citySealCopied')]});
 return {...base,premise:base.premise+' Explore Eldervale’s twelve districts and the persistent upper buried city.',initialFlags,locations,interactions,encounters:[...base.encounters,{id:'city-ward-sentinel',location:underId('ward'),resolvedFlag:'citySentinelResolved',enemy:{id:'city-ward-sentinel',name:'Old ward sentinel',ac:11,hp:14,initiativeModifier:0,attackBonus:2,damageDice:[1,4],damageModifier:0},opening:'The old ward sentinel rises from its broken line. The side gallery was a safe alternative; this street must now be defended.',victoryText:'The sentinel dissolves and does not return. Ward Street is safe for backtracking.'}],story:{...base.story,npcs,clues:{...base.story.clues,'city-descent-briefing':{fact:'The Last Lantern provides a maintained descent and a safe return stair into the upper buried city.',essential:true,unlocks:'Controlled Last Lantern descent',sources:[{location:'city-delvers-last',methods:['Read descent safety ledger'],outcome:'Record the upper-city briefing.'},{location:'city-delvers-maps',methods:['Read public survey folio'],outcome:'Independently record the same briefing.'}]},'city-gate-operation':{fact:'Read the workshop instructions or refuge chart, then turn the marked wheel to align the bronze arrows.',essential:true,unlocks:'Public first-city archive',sources:[{location:underId('refuge'),methods:['Read return route chart'],outcome:'Establish safe gate operation.'},{location:underId('wheel'),methods:['Read gate instructions'],outcome:'Independently establish the same gate operation.'}]}}}};
}
