import { assertValidAdventure } from "../adventure-schema.mjs";

const feature = (id, label, kind = "scenery") => ({ id, label, kind });
const exit = (to, via, options = {}) => ({ to, via, ...options });

export const lanternBelowAdventure = assertValidAdventure({
  schemaVersion: 1,
  id: "lantern-below",
  title: "The Lantern Below",
  series: "The Hollow Road",
  episode: 1,
  stateKey: "clueStage",
  startLocation: "outside-inn",
  initialFlags: { privateRoomPermission:false, pantryPermission:false, letterOpened:false, suppliesLocated:false, miteAwake:false, inkOffered:false, mapDrawn:false, guardianDefeated:false, maraRescued:false, adventureComplete:false },
  initialResources: { ink:1 },
  mapHeight: 760,
  premise: "A silver-moth letter leads the company beneath an old Eldervale inn without revealing the forgotten road beyond it too early.",
  principles: [
    "The physical layout is authoritative; observing a neighbouring room never moves the party.",
    "A room can only be entered through a listed exit after its requirements are satisfied.",
    "Clues reveal one actionable step at a time and never disclose an unreached room.",
    "Doors, containers, collected items, hazards, and completed scenes retain their state.",
    "A failed search describes uncertainty, never proof that an unseen danger is absent.",
  ],
  story: {
    dramaticQuestion: "Can the company follow Mara Vey's deliberately hidden trail, survive the awakened ward beneath the inn, and bring her back without exposing the old road to the wrong people?",
    playerPromise: "A warm, grounded fantasy mystery in which observation, conversation, practical problem-solving, and class abilities can all move the investigation forward.",
    fixedTruths: [
      { id: "letter-sent-by-mara", statement: "Mara Vey arranged for the silver-moth letter to reach a company likely to honour the old road." },
      { id: "mara-alive", statement: "Mara is alive but trapped in the collapsed survey alcove." },
      { id: "innkeeper-innocent", statement: "Innkeeper Tamsin Reed is protective of the inn and its guests but is not responsible for Mara's disappearance." },
      { id: "route-awakened", statement: "A dormant ward-road anchor beneath the Crooked Lantern has begun operating again." },
      { id: "mite-is-map", statement: "The ink-mite remembers routes it has travelled and draws them after receiving warmth and fresh ink." },
      { id: "guardian-bound", statement: "The ink-dark guardian is bound to the disturbed anchor; direct lantern light weakens and repels it." },
      { id: "series-identity-hidden", statement: "The survey geometry resembles part of The Witness constellation, but nobody in this episode can identify that connection yet." },
    ],
    acts: [
      { id: "invitation", title: "The Unasked-For Message", stages: [0, 1], purpose: "Establish the company, the inn, Mara's message, and a reason to choose the hidden road.", pressure: "Tamsin values discretion; disruptive behaviour makes cooperation harder but never removes the letter or blocks the adventure." },
      { id: "living-map", title: "A Line Beneath the Lantern", stages: [2, 4], purpose: "Let the company interpret Mara's instructions and find one of several fair routes to the concealed cellar.", pressure: "The inn continues around the party, and attention from staff is a social complication rather than an automatic failure." },
      { id: "awakened-road", title: "The Mothglass Ward", stages: [5, 7], purpose: "Turn investigation into physical exploration and show that the old road is active, dangerous, and larger than this inn.", pressure: "Disturbing mechanisms carelessly can raise noise, damage supplies, or strengthen the guardian, but cannot erase essential evidence." },
      { id: "rescue", title: "Mara's Last Survey", stages: [8, 9], purpose: "Resolve the guardian and collapse through combat, ingenuity, negotiation, or careful rescue work.", pressure: "Failure changes the cost or creates a new immediate problem; it never silently kills Mara or resets progress." },
    ],
    npcs: {
      "tamsin-reed": {
        name: "Tamsin Reed",
        role: "Innkeeper of the Crooked Lantern",
        appearance: "Tamsin Reed is a broad-shouldered woman in her middle years, with iron-grey hair braided close at the nape. She wears a clean cream shirt beneath a dark green wool waistcoat, with a practical brown apron tied at her waist.",
        locations: ["inn", "kitchen"],
        goals: ["Protect guests and staff", "Keep strangers out of private work areas", "Understand why Mara vanished after asking about the pantry"],
        knows: ["Mara stayed at the inn eleven days ago", "Mara repeatedly sketched the pantry shelves", "The shelves predate Tamsin's family and sometimes admit a cold draught"],
        sharesWhen: "Polite questions earn ordinary facts. Showing Mara's signed note or earning Tamsin's trust earns the pantry observations. Trespass causes confrontation, not magical ignorance or an impassable story lock.",
        voice: "Practical, observant, dryly hospitable, and more concerned with safety than secrecy.",
        mustNotKnow: ["What lies beyond the cellar", "How the mothglass spindle works", "Who disturbed the wider ward network"],
        conversation: {
          publicFacts: [
            "The Crooked Lantern serves hot stew, dark bread, small beer, cider, and whatever roast is still available",
            "Tamsin Reed has kept the Crooked Lantern for eighteen years",
            "The taproom is public, while private rooms are available when guests ask and one is free",
            "The kitchen and pantry are staff work areas unless Tamsin grants permission",
            "The evening rain has made the inn busier than usual",
            "Tamsin knows of no public adventuring contract tonight; if travellers are seeking unusual local trouble, she suggests speaking somewhere quieter than the crowded taproom",
          ],
          conditionalFacts: [
            {requires:[{path:"discoveries",includes:"mara-stayed-at-inn"}],fact:"Mara Vey stayed at the inn eleven days ago and asked for privacy"},
            {requires:[{path:"flags.letterOpened",equals:true}],fact:"Tamsin recognises Mara Vey's signature on the opened note"},
            {requires:[{path:"discoveries",includes:"pantry-destination"}],fact:"Mara repeatedly measured the pantry shelves and asked about a cold draught"},
          ],
        },
      },
      "mara-vey": {
        name: "Mara Vey",
        role: "Surveyor of the old roads",
        locations: ["alcove"],
        goals: ["Survive the collapse", "Prevent the awakened road from harming Eldervale", "Learn who is disturbing the old anchors"],
        knows: ["How the letter and ink-mite trail work", "The pantry hatch and cellar route", "Lantern light repels the guardian", "Several old routes elsewhere in Eldervale are stirring"],
        sharesWhen: "Before rescue Mara can give short, urgent answers about the immediate danger. After rescue she explains this episode's findings but not the hidden series answer she does not yet know.",
        voice: "Exact, exhausted, brave, and accustomed to describing distances and physical evidence.",
        mustNotKnow: ["Chancellor Oris Vale is responsible", "The full identity or purpose of The Witness"],
      },
    },
    clues: {
      "mara-sent-message": {
        fact: "Mara sent the company a warning and instructions for waking the ink-mite.",
        essential: true,
        unlocks: "The company can deliberately choose whether to follow Mara's trail.",
        sources: [
          { location: "back-room", methods: ["Open and read the silver-moth letter", "Warm the intact wax gently enough to reveal Mara's pressed survey initials before opening it"], outcome: "Reveal Mara as sender and the written instructions; do not reveal the pantry destination yet." },
          { location: "inn", npc: "tamsin-reed", methods: ["Ask whether Mara left a message or expected visitors after establishing her name"], outcome: "Tamsin directs the party to the private room where the untouched letter waits." },
        ],
      },
      "wake-ink-mite": {
        fact: "Warmth and one drop of fresh ink wake the harmless ink-mite so it can draw a remembered route.",
        essential: true,
        unlocks: "The drawn route identifies the pantry shelves.",
        sources: [
          { location: "back-room", methods: ["Follow the letter's literal instructions using the lamp and inkwell", "Use suitable magical warmth and writing ink without burning the creature"], outcome: "The mite draws a route ending at the pantry shelves and nothing beyond them." },
          { location: "back-room", methods: ["Study the dormant creature with Arcana or naturalist knowledge after opening the letter"], outcome: "Explain the safe activation method, but require the party to choose whether to perform it." },
        ],
      },
      "pantry-destination": {
        fact: "Mara's route leads to one particular section of pantry shelving.",
        essential: true,
        unlocks: "The company has a justified reason to inspect the pantry and can seek permission or enter another way.",
        sources: [
          { location: "back-room", methods: ["Wake and follow the ink-mite's drawn map", "Compare the mite's incomplete line with the inn's visible layout"], outcome: "Identify the pantry shelves, not the hidden hatch or cellar." },
          { location: "inn", npc: "tamsin-reed", methods: ["Ask about Mara's behaviour", "Show Tamsin Mara's signed note and request help"], outcome: "Tamsin recalls Mara measuring and sketching the pantry shelves and may escort the party there." },
        ],
      },
      "concealed-hatch": {
        fact: "A recently used cellar hatch is concealed behind the pantry shelves.",
        essential: true,
        unlocks: "The party can open the hatch and descend to the cellar.",
        sources: [
          { location: "pantry", methods: ["Search the shelf section marked by the map", "Inspect scrape marks and test the shelving", "Track the cold draught at floor level"], outcome: "Discover the hatch and evidence of recent use without revealing what is below." },
          { location: "pantry", npc: "tamsin-reed", methods: ["Earn Tamsin's cooperation and ask about the old shelves"], outcome: "Tamsin identifies the draught and helps shift the shelf, surprised by the hatch." },
        ],
      },
      "mara-trail": {
        fact: "Mara passed through the cellar and marked the stone route toward the mothglass chamber.",
        essential: true,
        unlocks: "The company can follow a concrete trail rather than choosing a direction blindly.",
        sources: [
          { location: "cellar", methods: ["Follow Mara's survey marks", "Compare recent boot scuffs with the old dust", "Use the ink-mite near the survey marks"], outcome: "Establish Mara's direction of travel but not her fate." },
          { location: "cellar-passage", methods: ["Open the survey box", "Inspect the repeated survey geometry"], outcome: "Confirm Mara deliberately continued toward the mothglass chamber." },
        ],
      },
      "spindle-passage": {
        fact: "The brass lantern is a counterweighted spindle that opens a concealed passage in the wall seam.",
        essential: true,
        unlocks: "The party can reach Mara's final trail.",
        sources: [
          { location: "mothglass", methods: ["Follow Mara's upward survey arrow and inspect the lantern mounting", "Study the disturbed dust and wall seam", "Trace the counterweight mechanically or magically"], outcome: "Explain how the mechanism can be operated without operating it automatically." },
          { location: "mothglass", methods: ["Experiment cautiously with the mounted lantern"], outcome: "Open the passage; a clumsy attempt may make noise or cost time but does not destroy the route." },
        ],
      },
      "guardian-weakness": {
        fact: "The ink-dark guardian recoils from steady, direct lantern light.",
        essential: false,
        unlocks: "The guardian can be fought, held back, distracted with ink, or bypassed using light.",
        sources: [
          { location: "alcove", methods: ["Observe its reaction to the party's light", "Test it with a directed lantern beam", "Ask Mara what drove it back"], outcome: "Reveal the visible weakness without choosing the party's solution." },
          { location: "passage", methods: ["Inspect the pattern of ink streaks and untouched pools of lamplight"], outcome: "Foreshadow that the creature avoids direct light without revealing its full nature." },
        ],
      },
    },
    consequences: {
      trust: "Respectful dealings with Tamsin provide information, permission, supplies, and an escort. Trespass costs trust and brings a direct social confrontation, but Tamsin can still be persuaded with evidence.",
      failedInvestigation: "A failed search consumes time or yields an incomplete observation. Preserve the clue and make another listed route available; never assert that the clue does not exist.",
      noisyExploration: "Noise draws Tamsin or staff in the inn and makes the guardian more alert below. It does not relocate clues or create unrelated monsters.",
      guardian: "Combat can defeat it; steady light can hold it back; spilled ink can distract it; a clever warding approach can contain it. Each solution creates a different cost but permits the rescue.",
      rescue: "A failed rescue attempt shifts stones, causes minor harm, or requires a safer approach. Mara remains alive unless the players knowingly accept a clearly stated lethal risk.",
    },
    improvisation: {
      allowed: ["Minor patrons and staff who provide atmosphere but no new clues", "Food, drink, weather, ordinary furniture, and harmless sensory details", "Costs such as time, noise, strained trust, or spent mundane supplies", "Approaches that use established character abilities to reach an authored clue or outcome"],
      forbidden: ["Moving the letter or any clue to a more convenient room", "Inventing a second culprit, secret faction, monster, trap, or magic item", "Giving an NPC knowledge outside their authored knowledge", "Removing an essential clue because of one failed roll", "Revealing the next location before a listed source establishes it", "Identifying the campaign's hidden villain or The Witness in this episode"],
    },
  },
  discoveries: {
    "mara-stayed-at-inn": { name:"Tamsin remembers Mara" },
    "mara-sent-message": { name:"Mara's message read" },
    "mite-awake": { name:"Ink-mite awakened" },
    "pantry-destination": { name:"Pantry route drawn" },
    "concealed-hatch": { name:"Cellar hatch discovered" },
    "mara-trail": { name:"Mara's cellar trail established" },
    "spindle-passage": { name:"Spindle passage discovered" },
    "guardian-weakness": { name:"Guardian weakness established" },
  },
  interactions: [
    {
      id:"ask-tamsin-about-mara", idempotencyKey:"tamsin:mara", location:"inn", modes:["speak"], stage:0,
      verbs:["ask","tell","know","remember"], targets:["Tamsin about Mara","Mara Vey","surveyor","visitors"],
      matchAll:[["Mara","Mara Vey","surveyor","visitors"]],
      forbids:[{path:"flags.letterOpened",equals:true}],
      effects:[{op:"set",path:"flags.privateRoomPermission",value:true},{op:"add",path:"discoveries",value:"mara-stayed-at-inn"}],
      outcome:{message:"Tamsin remembers Mara Vey as a precise, rain-soaked surveyor who stayed eleven days ago. She offers the company the quiet private back room Mara requested, but claims no knowledge of where Mara went afterward.",publicFacts:["Mara stayed at the inn eleven days ago.","Tamsin permits the company to use the private back room."]},
    },
    {
      id:"request-private-room", idempotencyKey:"tamsin:private-room", location:"inn", modes:["act","speak"], stage:0,
      verbs:["ask","request","find","want","need","have","take","show","lead","follow","move","go","enter"], targets:["privacy","some privacy","somewhere private","private place","private space","private room","quiet private room","back room","secluded corner","quiet corner"],
      effects:[{op:"set",path:"flags.privateRoomPermission",value:true},{op:"set",path:"currentLocation",value:"back-room"},{op:"add",path:"visited",value:"back-room"}],
      outcome:{message:"Tamsin leads the company from the public taproom into a small private back room. Once the door closes, they notice a sealed silver-moth letter resting alone on the table.",publicFacts:["The company enters the private back room with Tamsin's permission.","A sealed silver-moth letter is visible on the table."]},
    },
    {
      id:"show-mara-note-to-tamsin", idempotencyKey:"tamsin:pantry-lead", location:"inn", modes:["speak"], stage:2,
      verbs:["show","ask","read"], targets:["Tamsin Mara note","Mara signed note","Mara letter","what Mara was investigating"],
      requires:[{path:"flags.letterOpened",equals:true}], effects:[{op:"set",path:"flags.pantryPermission",value:true},{op:"set",path:"knowledge.pantryLeadSource",value:"tamsin"},{op:"add",path:"discoveries",value:"pantry-destination"}],
      outcome:{message:"Tamsin reads Mara's signature twice. Eleven days ago, Mara kept measuring the pantry shelves and asking about a cold draught. Tamsin permits the company to inspect them through the kitchen, but claims no knowledge of what lies behind them.",publicFacts:["Tamsin identifies the pantry shelves as Mara's focus.","Tamsin permits access through the kitchen."]},
    },
    {
      id:"inspect-sealed-letter", idempotencyKey:"letter:inspect-sealed", location:"back-room", modes:["act"], stage:0,
      verbs:["inspect","examine","study","look","check"], targets:["sealed silver moth letter","silver moth seal","letter","unopened envelope","moth seal"],
      requires:[{path:"flags.letterOpened",equals:false}], once:false,
      outcome:{ message:"The silver-moth wax remains unbroken. The paper is dry despite the rain, and a faint scratch sounds within; nothing on the sealed exterior identifies the sender or contents.", publicFacts:["The silver-moth seal remains intact.","The sealed letter's sender and contents remain unknown."] },
    },
    {
      id:"open-silver-moth-letter", idempotencyKey:"letter:open", location:"back-room", modes:["act"], stage:1,
      verbs:["open","break","unseal","read"], targets:["sealed silver moth letter","silver moth seal","seal","letter","envelope","instructions","Mara's instructions","Mara's note","parchment"],
      requires:[{path:"flags.letterOpened",equals:false}], effects:[{op:"set",path:"flags.letterOpened",value:true},{op:"add",path:"discoveries",value:"mara-sent-message"}],
      outcome:{ message:"The seal breaks deliberately. Inside are Mara Vey's signed instructions and a tiny dormant ink-mite; the note explains that warmth and one drop of fresh ink will wake it, but names no destination.", publicFacts:["Mara Vey sent the letter.","The opened letter instructs the party to warm the dormant ink-mite and offer one drop of fresh ink."] },
      repeat:{message:"The letter is already open. Mara's instructions read: “Warm my silver moth over a flame, give what wakes inside one drop of fresh ink, and follow the line it draws.”",publicFacts:["The letter is already open.","Mara's instructions say to warm the ink-mite, give it one drop of fresh ink, and follow the line it draws."]},
    },
    {
      id:"reread-mara-instructions", idempotencyKey:"letter:reread", location:"back-room", modes:["act"], stage:1,
      verbs:["read","say","state","repeat","recite","tell"], targets:["instructions","Mara's instructions","Mara's note","note","letter","parchment","what do instructions say"],
      requires:[{path:"flags.letterOpened",equals:true}], once:false,
      outcome:{message:"Mara's instructions read: “Warm my silver moth over a flame, give what wakes inside one drop of fresh ink, and follow the line it draws.”",publicFacts:["Mara's instructions say to warm the ink-mite, give it one drop of fresh ink, and follow the line it draws."]},
    },
    {
      id:"locate-mite-supplies", idempotencyKey:"mite:locate-supplies", location:"back-room", modes:["act"], stage:1,
      verbs:["find","look","search","locate"], targets:["ink","inkwell","fresh ink and flame","inkwell and lamp","fresh ink","safe flame","ink and a lit lamp"],
      matchAll:[["ink","inkwell"],["light","heat","flame","lamp","torch","fire"]],
      requires:[{path:"flags.letterOpened",equals:true}], effects:[{op:"set",path:"flags.suppliesLocated",value:true}],
      outcome:{ message:"The fresh inkwell and oil lamp are only located within reach. The moth, flame, and ink remain unchanged; finding the supplies does not use them.", publicFacts:["A fresh inkwell and safe lamp flame are available.","Neither supply has been used."] },
    },
    {
      id:"warm-ink-mite", idempotencyKey:"mite:warm", location:"back-room", modes:["act"], stage:1,
      verbs:["warm","heat","hold"], targets:["silver moth","moth","seal","ink mite","letter","opened letter","parchment"],
      requires:[{path:"flags.letterOpened",equals:true}], effects:[{op:"set",path:"flags.miteAwake",value:true},{op:"add",path:"discoveries",value:"mite-awake"}],
      outcome:{ message:"Steady warmth wakes the tiny ink-mite. It uncurls and stirs beside Mara's note but draws nothing; the fresh inkwell remains untouched until deliberately offered.", publicFacts:["The harmless ink-mite is awake.","No ink has been offered and no route has been drawn."] },
    },
    {
      id:"offer-mite-ink", idempotencyKey:"mite:ink", location:"back-room", modes:["act"], stage:2,
      verbs:["offer","give","feed","place","apply","put"], targets:["ink mite","mite","silver moth"], instruments:["fresh ink","ink","drop of ink","inkwell"],
      requires:[{path:"flags.miteAwake",equals:true}], effects:[{op:"set",path:"flags.inkOffered",value:true},{op:"set",path:"flags.mapDrawn",value:true},{op:"add",path:"discoveries",value:"pantry-destination"}],
      blocked:{message:"The ink-mite is still dormant. Fresh ink will not make it draw until the opened letter's other instruction—steady warmth—has first awakened it.",publicFacts:["The ink-mite remains dormant and no route is drawn."]},
      outcome:{ message:"Given one deliberate drop of fresh ink, the mite draws a line on the paper ending at a particular section of pantry shelves elsewhere in the inn.", publicFacts:["The ink-mite draws a route ending at the pantry shelves.","The drawing reveals no cellar or later room."] },
    },
    {
      id:"follow-drawn-route-to-pantry", idempotencyKey:"map:follow-to-pantry", location:"back-room", modes:["act"], stage:2, priority:20,
      verbs:["follow","go","walk","move","head","travel"], targets:["drawn route","line to the pantry","map line","drawn path","pantry","pantry shelves"],
      requires:[{path:"flags.mapDrawn",equals:true}],
      effects:[
        {op:"set",path:"previousLocation",value:"kitchen"},
        {op:"set",path:"currentLocation",value:"pantry"},
        {op:"add",path:"visited",value:"inn"},
        {op:"add",path:"visited",value:"kitchen"},
        {op:"add",path:"visited",value:"pantry"},
        {op:"set",path:"objects.private-room-door.open",value:true},
        {op:"set",path:"objects.kitchen-door.open",value:true},
        {op:"set",path:"objects.pantry-door.open",value:true},
      ],
      outcome:{message:"Following the ink-mite's line, the company returns through the taproom, passes through the working kitchen, and reaches the pantry shelves marked by the drawing.",publicFacts:["The company follows the drawn route through the taproom and kitchen to the pantry.","The marked pantry shelves are now within reach."]},
    },
    {
      id:"study-drawn-route", idempotencyKey:"map:study", location:"back-room", modes:["act"], stage:2,
      verbs:["study","inspect","investigate","read","follow","look","see"], targets:["drawn route","line to the pantry","map line","drawn path"], representations:["pantry shelves"],
      requires:[{path:"flags.mapDrawn",equals:true}], once:false,
      blocked:{message:"No drawn route exists to study yet. The opened letter's instructions must be completed before the ink-mite can draw one.",publicFacts:["No route has been drawn."]},
      outcome:{ message:"The party studies the ink-mite's line here as a drawing. It identifies pantry shelves elsewhere in the inn; studying it neither places those shelves in this room nor moves the party.", publicFacts:["The drawing represents a route to the pantry shelves elsewhere in the inn."] },
    },
    {
      id:"discover-cellar-hatch", idempotencyKey:"pantry:hatch", location:"pantry", modes:["act"], stage:3,
      verbs:["search","inspect","investigate","examine","track","test","follow"], targets:["pantry shelves","shelf scrapes","scrape marks","cold draught","floor draught"],
      requires:[{path:"discoveries",includes:"pantry-destination"}], effects:[{op:"set",path:"objects.cellar-hatch.discovered",value:true},{op:"add",path:"discoveries",value:"concealed-hatch"}],
      outcome:{ message:"Scrapes beneath the marked shelving and a cold floor-level draught reveal a recently used cellar hatch. It remains closed, and nothing below is yet visible.", publicFacts:["A concealed cellar hatch has been discovered behind the pantry shelves.","The hatch is closed."] },
    },
    {
      id:"establish-mara-trail", idempotencyKey:"cellar:mara-trail", location:"cellar", modes:["act"], stage:4,
      verbs:["inspect","examine","follow","track","study"], targets:["survey marks","Mara trail","boot scuffs","old dust"],
      effects:[{op:"add",path:"discoveries",value:"mara-trail"}],
      outcome:{message:"Mara's fresh survey marks and boot scuffs establish that she continued through the locked stone door; they do not reveal her fate.",publicFacts:["Mara continued through the cellar's stone door."]},
    },
    {
      id:"discover-spindle-passage", idempotencyKey:"mothglass:spindle", location:"mothglass", modes:["act"], stage:7,
      verbs:["inspect","study","operate","turn","pull","use"], targets:["brass lantern","spindle","counterweight","wall seam"],
      effects:[{op:"set",path:"objects.spindle-door.discovered",value:true},{op:"set",path:"objects.spindle-door.open",value:true},{op:"add",path:"discoveries",value:"spindle-passage"}],
      outcome:{message:"The brass lantern turns on its counterweight. The wall seam opens into a concealed survey passage and remains open for backtracking.",publicFacts:["The spindle opens a concealed survey passage.","The passage remains open."]},
    },
    {
      id:"repel-guardian-with-light", idempotencyKey:"guardian:light", location:"alcove", modes:["act"], stage:9,
      verbs:["shine","direct","hold","use"], targets:["guardian","ink dark guardian"], instruments:["lantern","light","torch"],
      effects:[{op:"set",path:"flags.guardianDefeated",value:true},{op:"add",path:"discoveries",value:"guardian-weakness"}],
      outcome:{message:"Steady direct lantern light pins the ink-dark guardian against the old ward until it unravels, leaving a safe path to Mara.",publicFacts:["Direct lantern light defeats the guardian.","Mara can now be reached safely."]},
    },
    {
      id:"distract-guardian-with-ink", idempotencyKey:"guardian:ink", location:"alcove", modes:["act"], stage:9,
      verbs:["throw","spill","offer","use"], targets:["guardian","ink dark guardian"], instruments:["ink","inkwell"],
      requires:[{path:"resources.ink",minimum:1}], effects:[{op:"consume",path:"resources.ink",value:1},{op:"set",path:"flags.guardianDefeated",value:true}],
      outcome:{message:"The spilled ink draws the guardian away from Mara and into the old ward-lines, where it is contained long enough for rescue.",publicFacts:["Ink diverts and contains the guardian.","Mara can now be reached safely."]},
    },
    {
      id:"rescue-mara", idempotencyKey:"mara:rescue", location:"alcove", modes:["act"], stage:10,
      verbs:["rescue","free","help","pull","clear"], targets:["Mara","Mara Vey","loose stones","collapsed alcove"],
      requires:[{path:"flags.guardianDefeated",equals:true}], effects:[{op:"set",path:"flags.maraRescued",value:true},{op:"set",path:"flags.adventureComplete",value:true}],
      outcome:{message:"With the guardian resolved, the company clears the unstable stones and frees Mara Vey. The Lantern Below is complete, and Mara's survey of the wider old road carries forward.",publicFacts:["Mara Vey is rescued.","The adventure is complete."]},
    },
  ],
  locations: {
    "outside-inn": {
      name: "Outside the Crooked Lantern",
      aliases: ["outside the inn", "outside the tavern", "outside the pub", "the street"],
      description: "A rain-dark street beneath the inn's creaking silver-lantern sign.",
      stage: 0,
      arrivalStage: 0,
      map: { x: 4, y: 24, w: 18, h: 26, kind: "road" },
      features: [
        feature("inn-sign", "creaking inn sign"),
        feature("front-door", "public front door", "door"),
        { ...feature("taproom-windows", "lit taproom windows", "window"), observation:"Through the rain-streaked windows, the company can see a busy public taproom: a bar, a bright hearth, scattered tables, supper, and patrons in conversation. Looking through the glass does not move the company from the street." },
      ],
      exits: [exit("inn", "public front door", { object: "front-door", message:"The company enters the Crooked Lantern's busy public taproom through the front door." })],
    },
    inn: {
      name: "The Crooked Lantern Taproom",
      aliases: ["the Crooked Lantern", "the inn", "the tavern", "the pub", "inside the inn", "inside the tavern", "inside the pub", "taproom"],
      description: "A busy public room with a bar, hearth, scattered tables, patrons, and doors to the inn's private areas.",
      occupants: ["ordinary patrons", "two taproom staff"],
      entryBeats: [{id:"tamsin-welcome",npc:"tamsin-reed",text:"As the company enters the public taproom, Tamsin Reed looks up from behind the bar and gives the rain-soaked travellers a practical once-over. “Evening. Food, drink, or somewhere quiet to sit?”"}],
      stage: 0,
      arrivalStage: 1,
      map: { x: 25, y: 12, w: 27, h: 30, kind: "taproom" },
      features: [
        feature("front-door", "public entrance", "door"),
        feature("taproom-bar", "bar"),
        feature("taproom-hearth", "hearth"),
        feature("taproom-tables", "public tables"),
        feature("private-room-door", "private-room door", "door"),
        feature("kitchen-door", "staff kitchen door", "door"),
      ],
      exits: [
        exit("outside-inn", "public front door", { object: "front-door" }),
        exit("back-room", "private-room door", { object: "private-room-door", requires:[{path:"flags.privateRoomPermission",equals:true}] }),
        exit("kitchen", "staff kitchen door", { object: "kitchen-door", requires:[{path:"flags.pantryPermission",equals:true}] }),
      ],
    },
    "back-room": {
      name: "Private Back Room",
      aliases: ["private room", "quiet room", "back room", "secluded room"],
      description: "A small private room with a writing desk, oil lamp, fresh inkwell, and a worn wooden table.",
      stage: 0,
      arrivalStage: 2,
      map: { x: 56, y: 10, w: 18, h: 21, kind: "private-room" },
      features: [
        feature("private-room-door", "door to the taproom", "door"),
        { ...feature("private-table", "private table"), observation:"The private table is otherwise bare. The sealed silver-moth letter rests alone on its worn wooden surface.", contents:["the sealed silver-moth letter"], presentations:[
          { requires:[{path:"itemOwners.silver-moth-letter",truthy:true}], observation:"The private table is otherwise bare; the silver-moth letter is now being carried.", contents:["nothing else of note"] },
          { requires:[{path:"flags.letterOpened",equals:true}], observation:"The private table is otherwise bare. Mara Vey's opened letter, its instructions, and the tiny ink-mite rest on its worn wooden surface.", contents:["Mara Vey's opened letter", "the written instructions", "the tiny ink-mite"] },
        ] },
        feature("writing-desk", "writing desk"),
        feature("room-lamp", "oil lamp"),
        feature("fresh-inkwell", "fresh inkwell"),
        { ...feature("silver-moth-letter", "sealed silver-moth letter", "clue"), presentations:[
          { requires:[{path:"flags.letterOpened",equals:true}], label:"Mara Vey's opened silver-moth letter" },
        ] },
      ],
      exits: [exit("inn", "private-room door", { object: "private-room-door" })],
    },
    kitchen: {
      name: "The Crooked Lantern Kitchen",
      description: "A working kitchen behind the taproom. Cupboards, a preparation table, and a separate pantry door are visible here.",
      stage: 2,
      arrivalStage: 2,
      map: { x: 25, y: 47, w: 23, h: 22, kind: "kitchen" },
      features: [
        feature("kitchen-door", "door to the taproom", "door"),
        feature("kitchen-table", "preparation table"),
        feature("kitchen-cupboards", "cupboards"),
        feature("kitchen-hearth", "cooking hearth"),
        feature("pantry-door", "pantry door", "door"),
      ],
      exits: [
        exit("inn", "staff kitchen door", { object: "kitchen-door" }),
        exit("pantry", "pantry door", { object: "pantry-door" }),
      ],
    },
    pantry: {
      name: "Pantry",
      description: "A cramped store room lined with shelves and jars; the ink-mite's route ends at one particular shelving section.",
      stage: 2,
      arrivalStage: 2,
      map: { x: 51, y: 46, w: 19, h: 20, kind: "pantry" },
      features: [
        feature("pantry-door", "door to the kitchen", "door"),
        feature("pantry-shelves", "pantry shelves", "clue"),
        feature("shelf-scrapes", "scrape marks beneath the pantry shelves", "clue"),
        feature("floor-draught", "cold floor-level draught", "clue"),
        feature("pantry-jars", "dusty jars"),
        feature("cellar-hatch", "concealed cellar hatch", "door"),
      ],
      exits: [
        exit("kitchen", "pantry door", { object: "pantry-door" }),
        exit("cellar", "concealed cellar hatch", {
          object: "cellar-hatch",
          requires: [{ path: "objects.cellar-hatch.open", equals: true }],
        }),
      ],
    },
    cellar: {
      name: "Cellar",
      description: "Stone steps descend to barrels, old survey marks, and a locked stone door at the rear of the cellar.",
      stage: 3,
      arrivalStage: 2,
      map: { x: 51, y: 71, w: 22, h: 23, kind: "cellar" },
      features: [
        feature("cellar-hatch", "stairs up to the pantry", "door"),
        feature("cellar-barrels", "barrels"),
        feature("survey-marks", "old survey marks", "clue"),
        feature("keyed-stone-door", "locked stone door", "door"),
      ],
      exits: [
        exit("pantry", "cellar stairs", { object: "cellar-hatch" }),
        exit("cellar-passage", "stone door", {
          object: "keyed-stone-door",
          requires: [{ path: "objects.keyed-stone-door.open", equals: true }],
        }),
      ],
    },
    "cellar-passage": {
        name: "The Cellar Passage",
      description: "A narrow passage beyond the opened stone door bearing Mara Vey's abandoned survey mark.",
      stage: 4,
      arrivalStage: 2,
      map: { x: 76, y: 73, w: 14, h: 18, kind: "passage" },
      features: [
        feature("keyed-stone-door", "open stone door", "door"),
        feature("passage-marks", "survey marks"),
        feature("survey-box", "rusted survey box", "container"),
        feature("mothglass-entry", "mothglass chamber entrance", "door"),
      ],
      exits: [
        exit("cellar", "stone door", { object: "keyed-stone-door" }),
        exit("mothglass", "mothglass chamber entrance", { object: "mothglass-entry" }),
      ],
    },
    mothglass: {
      name: "Mothglass Chamber",
      description: "An old chamber dominated by a brass lantern mounted on a counterweighted spindle and a visible seam in the wall.",
      stage: 5,
      arrivalStage: 2,
      map: { x: 74, y: 46, w: 20, h: 21, kind: "chamber" },
      features: [
        feature("mothglass-entry", "entrance from the cellar passage", "door"),
        feature("spindle-lantern", "counterweighted brass lantern", "mechanism"),
        feature("wall-seam", "vertical wall seam", "clue"),
        feature("spindle-door", "concealed passage", "door"),
      ],
      exits: [
        exit("cellar-passage", "mothglass chamber entrance", { object: "mothglass-entry" }),
        exit("passage", "concealed passage", {
          object: "spindle-door",
          requires: [{ path: "objects.spindle-door.open", equals: true }],
        }),
      ],
    },
    passage: {
      name: "Concealed Survey Passage",
      description: "A cramped survey passage where recent boot prints and a streak of dried black ink lead toward a collapse.",
      stage: 7,
      arrivalStage: 2,
      map: { x: 52, y: 98, w: 38, h: 14, kind: "passage" },
      features: [
        feature("spindle-door", "concealed door", "door"),
        feature("recent-bootprints", "recent boot prints", "clue"),
        feature("dried-black-ink", "dried black ink", "clue"),
        feature("alcove-opening", "collapsed survey alcove", "door"),
      ],
      exits: [
        exit("mothglass", "concealed door", { object: "spindle-door" }),
        exit("alcove", "collapsed survey alcove", { object: "alcove-opening" }),
      ],
    },
    alcove: {
      name: "Collapsed Survey Alcove",
      description: "Loose stones block Mara Vey in a damaged survey alcove while an ink-dark guardian bars a safe rescue.",
      stage: 8,
      arrivalStage: 2,
      map: { x: 35, y: 98, w: 14, h: 16, kind: "alcove" },
      features: [
        feature("alcove-opening", "opening to the passage", "door"),
        feature("loose-stones", "unstable loose stones", "hazard"),
        feature("mara-vey", "Mara Vey", "npc"),
        feature("ink-guardian", "ink-dark guardian", "creature"),
      ],
      exits: [exit("passage", "survey passage", { object: "alcove-opening" })],
    },
  },
  objects: {
    "front-door": { name: "Crooked Lantern front door", type: "door", locations: ["outside-inn", "inn"], initial: { locked: false, open: false } },
    "private-room-door": { name: "private-room door", type: "door", locations: ["inn", "back-room"], initial: { locked: false, open: false } },
    "kitchen-door": { name: "kitchen door", type: "door", locations: ["inn", "kitchen"], initial: { locked: false, open: false } },
    "pantry-door": { name: "pantry door", type: "door", locations: ["kitchen", "pantry"], initial: { locked: false, open: false } },
    "cellar-hatch": { name: "concealed cellar hatch", type: "door", locations: ["pantry", "cellar"], initial: { discovered: false, locked: false, open: false } },
    "keyed-stone-door": { name: "keyed stone door", type: "door", locations: ["cellar", "cellar-passage"], key: "cellar-key", initial: { locked: true, open: false } },
    "mothglass-entry": { name: "mothglass chamber entrance", type: "door", locations: ["cellar-passage", "mothglass"], initial: { locked: false, open: true } },
    "spindle-door": { name: "concealed spindle door", type: "door", locations: ["mothglass", "passage"], initial: { discovered: false, locked: false, open: false } },
    "alcove-opening": { name: "collapsed survey alcove opening", type: "door", locations: ["passage", "alcove"], initial: { locked: false, open: true } },
  },
  containers: {
    "survey-box": {
      name: "rusted survey box",
      location: "cellar-passage",
      key: "cellar-key",
      initial: { discovered: false, locked: true, open: false },
      items: ["glowing-key"],
      oneShot: true,
    },
  },
  items: {
    "silver-moth-letter": { name: "Silver-moth letter", aliases:["letter","Mara's letter","Mara's note","envelope","parchment"], location: "back-room", portable: true, unique: true },
    "room-lantern": { name: "Lantern", location: "back-room", portable: true, unique: false },
    torch: { name: "Torch", location: "back-room", portable: true, unique: false },
    map: { name: "Map", location: "cellar-passage", portable: true, unique: true },
    "cellar-key": { name: "Cellar key", location: "cellar", portable: true, unique: true },
    "glowing-key": { name: "Glowing survey key", location: "cellar-passage", container: "survey-box", portable: true, unique: true },
  },
  scenes: {
    arrival: { location: "outside-inn", summary: "The company arrives outside in the rain; the inn interior is only visible through windows." },
    taproom: { location: "inn", requires: [{ path: "visited", includes: "inn" }], summary: "The company enters the public taproom and can interact before seeking privacy." },
    letter: { location: "back-room", requires: [{ path: "visited", includes: "back-room" }], summary: "The sealed letter appears only after the party deliberately reaches the private room." },
    pantry: { location: "pantry", requires: [{ path: "flags.mapDrawn", equals: true }], summary: "The drawn line identifies the pantry shelves, not the cellar itself." },
    cellar: { location: "cellar", requires: [{ path: "objects.cellar-hatch.open", equals: true }], summary: "The party descends only after discovering and opening the cellar hatch." },
    mothglass: { location: "mothglass", requires: [{ path: "objects.keyed-stone-door.open", equals: true }], summary: "The spindle mechanism is inspected before it can reveal the next passage." },
    rescue: { location: "alcove", requires: [{ path: "visited", includes: "alcove" }], summary: "The guardian and unstable stones must be resolved before Mara is freed." },
  },
  milestones: {
    complete: {
      name: "Mara Vey rescued",
      requires: [
        { path: "flags.guardianDefeated", equals: true },
        { path: "flags.maraRescued", equals: true },
      ],
      nextAdventure: "ashes-of-briarwatch",
    },
  },
});

export default lanternBelowAdventure;
