// Stonecross extends the existing ferry save. Local content uses the shared
// authored interaction, atlas, conversation and combat systems only.
const flag=(name,value=true)=>({path:"flags."+name,equals:value});
const set=(name,value=true)=>({op:"set",path:"flags."+name,value});
const known=flag("stonecrossBellKnown"), restored=flag("stonecrossBellRestored");
const calm=flag("stonecrossRatsResolved");
const scenery=(id,label,observation,extra={})=>({id,label,kind:"scenery",observation,...extra});
export const stonecrossPlaces=[
  {id:"ferry",name:"Stonecross Ferry",x:59,y:34,aliases:["ferry landing","Stonecross landing"],npc:"ferryman",
    description:"A timber ferry landing fronts the river. Jory watches a frayed mooring; spare rope and the landing ring are within reach. Paths lead to his hut, the Reed & Oar inn, boatyard, coach stop and reedbank.",
    presentations:[{requires:[flag("ferryRepaired")],description:"Stonecross Ferry is back in service. Jory tends the sound mooring beside the landing. Local paths and the public roads to Rivergate and Willowford remain open."}],
    features:[scenery("mooring","ferry mooring","The mooring is frayed. Sound spare rope and a landing ring are within reach.",{presentations:[{requires:[flag("ferryRepaired")],observation:"Sound rope is securely tied to the landing ring. The repaired mooring holds the ferry safely."}]}),scenery("stonecross-wayboard","landing wayboard","Public paths connect the hut, inn, boatyard, coach stop and reedbank. Roads connect Rivergate Market and Willowford.")]},
  {id:"stonecross-hut",name:"Ferryman's Hut",x:47,y:23,aliases:["ferryman hut","Jory's hut"],description:"A modest hut shelters a public crossing log, a dry bench and a wall of river-height notches. Jory works outside at the landing.",features:[scenery("crossing-log","crossing log","The log records ordinary river heights and the public crossings to Rivergate and Willowford. It is not a boat timetable or a secret survey ledger."),scenery("river-notches","river-height notches","Years of flood marks show why riverfolk value an early warning. Looking does not change the water or forecast a timed flood.")]},
  {id:"stonecross-inn",name:"The Reed & Oar",x:31,y:29,aliases:["Reed and Oar","Reed & Oar","riverside inn"],npc:"stonecross-host",description:"A thatched riverside inn smells of oatcakes and woodsmoke. Its host tends the public room; a river journal lies open beside the hearth.",features:[scenery("river-journal","river journal","The inn's river journal records a storm-damaged warning bell and large marsh rats nesting around the old boathouse. Read it to investigate the problem; observation does not repair anything."),scenery("inn-hearth","inn hearth","Travellers warm their hands and exchange ordinary road news here. No lodging purchase, healing or resource recovery is implemented.")]},
  {id:"stonecross-boatyard",name:"Pikebank Boatyard",x:47,y:57,aliases:["boatyard","boatwright's yard"],npc:"stonecross-boatwright",description:"Timber ribs and unfinished hulls fill an open work yard. Edda keeps a storm-damage report on her bench.",features:[scenery("timber-report","storm-damage report","Edda's report identifies a fallen beam jamming the old boathouse's warning bell, with marsh rats nesting beneath it. Examine the report for a safe route and repair advice."),scenery("boat-ribs","unfinished boat ribs","The boatwright's timber and tools are not free equipment. Work on a hull does not create an unestablished boat journey.")]},
  {id:"stonecross-coach",name:"Stonecross Coach Stop",x:21,y:53,aliases:["coach stop","Stonecross coach yard"],npc:"stonecross-driver",description:"A small stable court gives road travellers a place to meet the public carriage. Bran checks a harness beside the route board.",features:[scenery("stonecross-coach-board","coach route board","Established carriages connect this stop to Rivergate Market, Eldervale City and Willowford Coach Yard. First visit all connecting stops and repair the ferry mooring. The introductory service has no fare.")]},
  {id:"stonecross-reeds",name:"Reedbank Path",x:70,y:73,aliases:["reedbank","reeds","riverside path"],description:"A quiet path follows the reeds. A covered feeding bowl and a measured basket of waste grain are kept here to draw nuisance animals away from working boats.",features:[scenery("feeding-bowl","covered feeding bowl","The bowl can be baited with the waste grain already beside it. This lures known nuisance animals away from the old boathouse; it is a deliberate action, not an automatic effect of looking.",{presentations:[{requires:[flag("stonecrossBaitPlaced")],observation:"The measured waste grain has been used to draw the marsh rats away. They remain out in the reeds; no more bait is needed."}]}),scenery("waste-grain","measured waste grain","This local waste-grain basket is reserved for the feeding bowl, not a takeable inventory supply.")]},
  {id:"stonecross-boathouse",name:"Old Bell Boathouse",x:82,y:88,aliases:["old boathouse","bell boathouse","warning bell"],requires:[known],
    description:"A storm-battered boathouse stands beyond the reedbank. A fallen beam jams its river-warning bell; large marsh rats crowd the timber underneath.",
    presentations:[{requires:[restored],description:"The fallen beam is secured and the river-warning bell hangs free. The boathouse is safe to revisit; the resolved marsh-rat encounter does not return."},{requires:[calm],description:"The marsh rats no longer bar the boathouse. A fallen beam still jams the river-warning bell, ready for a careful repair."}],
    features:[scenery("bell-frame","warning bell frame","A fallen beam jams the warning bell. Deal with the marsh rats before securing the beam and freeing the bell.",{presentations:[{requires:[restored],observation:"The beam is secured, the bell hangs free and the warning mechanism is restored."},{requires:[calm],observation:"The rats are gone. Use the repair advice to secure the fallen beam and free the warning bell."}]})]},
];
export const stonecrossLinks=stonecrossPlaces.filter(p=>p.id!=="ferry"&&p.id!=="stonecross-boathouse").map(p=>["ferry",p.id]).concat([["stonecross-boatyard","stonecross-reeds"],["stonecross-reeds","stonecross-boathouse"]]);
const community=[
  "Stonecross has public paths to the ferryman's hut, Reed & Oar inn, Pikebank Boatyard, coach stop and reedbank. Regional roads lead through the landing to Rivergate and Willowford.",
  "Jory Pike works at the landing, Mira Sedge hosts the inn, Edda Quill is the boatwright and Bran Tiller drives from the coach stop. These are usual workplaces, not knowledge of off-scene current whereabouts.",
  "The ferry mooring and river-warning bell are separate repairs. Restoring one never completes the other.",
  "Purchases, paid rooms, boat hire, schedules and healing are not implemented. The residents cannot grant unrecorded rewards or main-story progress.",
];
const status=[
  {requires:[flag("ferryRepaired",false)],fact:"The ferry mooring is frayed. Spare rope and the landing ring are within reach at the landing."},
  {requires:[flag("ferryRepaired")],fact:"The company repaired the ferry mooring. The crossing remains in service; the warning bell is a separate job."},
  {requires:[flag("stonecrossBellRestored",false)],fact:"The river-warning bell is damaged. Ask Jory about the bell or local work; the inn's journal and boatyard's damage report offer independent investigations."},
  {requires:[known,flag("stonecrossBellRestored",false)],fact:"The old bell boathouse lies beyond the reedbank. Investigate repair advice, then use the feeding bowl at the reedbank to lure away the rats or face the encounter at the boathouse. Physically repair the bell there, then report back to Jory."},
  {requires:[restored],fact:"The company restored the warning bell. The boathouse is safe, but no new ferry or main-story reward was granted."},
];
const character=(name,role,location,portraitId,appearance,voice,publicBackground,greeting,facts=[])=>({name,role,locations:[location],portraitId,appearance,voice,publicBackground,greeting,
  goals:["Keep Stonecross safe and welcoming","Offer truthful local advice"],knows:[...community,...facts],mustNotKnow:["Hidden campaign answers, unseen current whereabouts or invented transport services"],conversation:{publicFacts:[...community,...facts],conditionalFacts:status}});
export const stonecrossNpcs={
  ferryman:character("Jory Pike","Stonecross ferryman","ferry","jory","Weathered face, greying brown hair and a dark blue working tunic.","Plain-spoken, patient and grateful for practical help.","Jory Pike runs Stonecross Ferry. A patient, practical river worker, he cares about sound ropes, safe crossings and the people who depend on them.","Jory nods from the landing. “There's more to Stonecross than the crossing. Visit the inn or Edda's yard; if you're looking to help, ask me about the warning bell.”"),
  "stonecross-host":character("Mira Sedge","Reed & Oar innkeeper","stonecross-inn","mira","Dark curls, russet blouse and a cream working apron.","Warm, gently humorous and attentive to travellers.","Mira Sedge keeps the Reed & Oar. She enjoys hearing travellers' accounts and keeps a river journal beside the hearth.","Mira sets down a cloth. “Welcome in. The journal has our river news. Ask about the bell if you fancy something more useful than listening to me complain about the weather.”",["Mira records witnessed river events, not distant main-campaign secrets."]),
  "stonecross-boatwright":character("Edda Quill","Pikebank boatwright","stonecross-boatyard","edda","Short silver hair, freckled face and a scuffed leather apron.","Thoughtful, capable and precise about practical safety.","Edda Quill builds and repairs riverboats at Pikebank. She approaches damaged timber with patience, careful observation and respect for the river.","Edda brushes shavings from her bench. “The bell's beam is jammed, not rotten. Read my damage report before you go hauling anything. Those marsh rats won't welcome an interruption.”",["Edda's storm-damage report records how to secure the beam without damaging the bell."]),
  "stonecross-driver":character("Bran Tiller","Stonecross coach driver","stonecross-coach","bran","Closely cropped hair, tan coat and dark green neck scarf.","Cheerful, clear about actual road connections.","Bran Tiller drives the public carriage from Stonecross's stable court. He likes a familiar road and a well-tended harness.","Bran checks a buckle. “City, Rivergate or Willowford—once the connecting road's familiar and Jory's mooring is sound. The board tells you what's available.”",["The warning-bell task is optional and does not unlock carriage travel; only the existing crossing and journey requirements govern it."]),
};
stonecrossNpcs.ferryman.conversation.conditionalFacts.push(
  {requires:[flag("ferryRepaired",false)],fact:"The mooring is frayed; secure the spare rope already at the landing to its ring. No money or special tool is required."},
  {requires:[flag("ferryRepaired")],fact:"The company repaired the mooring and the ferry remains in service."});
stonecrossNpcs["stonecross-boatwright"].conversation = {
  ...stonecrossNpcs["stonecross-boatwright"].conversation,
  conditionalFacts:[...status,
    {requires:[flag("stonecrossRatsResolved",false)],fact:"Marsh rats are nesting around the damaged bell. Read Edda's storm-damage report before attempting the repair."},
    {requires:[calm],fact:"The marsh rats have been dealt with and no longer bar the bell repair."}],
};
export const stonecrossLocations=Object.fromEntries(stonecrossPlaces.map((place,index)=>[place.id,{
  name:place.name,description:place.description,stage:0,aliases:[place.name,...place.aliases],requires:place.requires||[],presentations:place.presentations||[],
  map:{x:300+(index%3)*26,y:10+Math.floor(index/3)*22,w:18,h:14,kind:"outdoor",label:place.name},
  features:[...place.features,...(place.npc?[{id:place.npc,label:stonecrossNpcs[place.npc].name,kind:"npc"}]:[])],
  occupants:place.id==="ferry"?["riverfolk waiting beside the landing"]:place.id==="stonecross-inn"?["travellers resting by the hearth"]:[],
  ...(place.id==="ferry"?{ambientGreeting:"A waiting traveller returns the greeting and points to the landing wayboard."}:{}),
  exits:stonecrossLinks.filter(link=>link.includes(place.id)).map(link=>{const to=link.find(id=>id!==place.id);return {to,via:"footpath to "+stonecrossPlaces.find(p=>p.id===to).name,...(to==="stonecross-boathouse"?{requires:[known]}:{})};}),
  entryBeats:place.npc?[{id:place.npc+"-stonecross-welcome",npc:place.npc,text:stonecrossNpcs[place.npc].greeting,...(["stonecross-host","stonecross-boatwright"].includes(place.npc)?{requires:[flag("stonecrossBellRestored",false)]}:{})},...(["stonecross-host","stonecross-boatwright"].includes(place.npc)?[{id:place.npc+"-stonecross-restored-welcome",npc:place.npc,requires:[restored],text:stonecrossNpcs[place.npc].name+" welcomes the company. “Thank you for restoring the river-warning bell. It is good to have you here.”"}]:[]),...(place.id==="ferry"?[{id:"ferryman-welcome",npc:"ferryman",requires:[flag("ferryRepaired",false)],text:"Jory lifts a frayed rope. “Boat's sound; this isn't. There's spare rope on the landing. Help me secure the mooring and we'll have the crossing working again.”"}]:[])]:[],
}]));
const interaction=(id,location,modes,verbs,targets,effects,message,extra={})=>({id,location,modes,verbs,targets,effects,outcome:{message},...extra});
const reveal=[set("stonecrossBellKnown"),{op:"add",path:"discoveries",value:"stonecross-bell-site"}];
const diagnosis=[...reveal,set("stonecrossBellEvidence"),{op:"add",path:"discoveries",value:"stonecross-bell-advice"}];
export const stonecrossInteractions=[
  interaction("stonecross-bell-invitation","ferry",["act","speak"],["ask","request"],["bell","work","trouble","help"],reveal,
    "Jory explains that the river-warning bell has gone silent at the old boathouse beyond the reedbank. Read Mira's river journal at the inn or Edda's damage report at the boatyard. Lure the marsh rats away using the reedbank feeding bowl, or face them at the boathouse. Repair the bell there, then report back. The ferry mooring is a separate job.",
    {requires:[flag("stonecrossBellRestored",false)],repeat:{message:"Jory's bell request is recorded: investigate the journal or damage report, reach the boathouse through the reedbank, deal with the rats and repair the beam before reporting. A completed repair stays complete."}}),
  ...[["stonecross-inn",["river journal","bell news"]],["stonecross-boatyard",["storm-damage report","damage report","bell advice"]]].map(([location,targets])=>interaction("stonecross-investigate-"+location,location,["act"],["read","inspect","examine","study","check"],targets,diagnosis,
    "The account confirms a fallen beam jammed the old boathouse's warning bell. Secure the beam before freeing the bell. The reedbank leads there; its feeding bowl can lure the marsh rats away, otherwise entering the boathouse starts an encounter. This investigation moves nothing and repairs nothing.",
    {repeat:{message:"The original damage was a jammed beam at the old bell boathouse, reached through the reedbank. Secure it and free the bell once the rats are resolved. Any completed repair remains complete; reading never undoes it."}})),
  interaction("stonecross-lure-rats","stonecross-reeds",["act"],["bait","fill","lure","draw"],["feeding bowl","bowl","marsh rats","rats"],[set("stonecrossBaitPlaced"),set("stonecrossRatsResolved"),set("stonecrossBellApproach","lured")],
    "The company places the measured waste grain in the feeding bowl. The marsh rats leave the boathouse for the far reeds and remain away from its working area. The boathouse can be approached safely; the beam and bell still need a physical repair there.",
    {requires:[known,flag("stonecrossRatsResolved",false)],blocked:{message:"First establish the boathouse problem through Jory, the inn journal or the damage report. An already-resolved encounter needs no more bait."},repeat:{message:"The marsh rats remain resolved. No further grain is used and a completed repair is not undone."}}),
  interaction("stonecross-repair-bell","stonecross-boathouse",["act"],["repair","secure","free","clear","fix"],["warning bell","bell frame","fallen beam"],[set("stonecrossBellRestored"),{op:"add",path:"discoveries",value:"stonecross-bell-restored"}],
    "Following the recorded repair advice, the company secures the fallen beam and frees the warning bell. Its clear test-note carries across the river. The bell is restored, not a second ferry crossing. Return to Jory at the landing to report the work.",
    {requires:[flag("stonecrossBellEvidence"),calm],blocked:{message:"Read the inn's journal or the boatyard's damage report for repair advice, and resolve the marsh rats before working on the beam."},repeat:{message:"The warning bell remains restored and the beam secure. No second repair or reward is granted."}}),
  interaction("stonecross-report-bell","ferry",["act","speak"],["tell","report","share"],["bell","repair news"],[set("stonecrossBellReported")],
    "Jory listens for the bell and thanks the company. “The river gives enough surprises without losing our warning. You'll always find a welcome at this landing.” Stonecross remembers the help; the saved main adventure and earned levels are unchanged.",
    {requires:[restored],blocked:{message:"Restore the warning bell at the boathouse before reporting success to Jory."},repeat:{message:"Jory remembers the restored warning bell and welcomes another conversation. No duplicate reward is awarded."}}),
];
export const stonecrossFlags={stonecrossBellKnown:false,stonecrossBellEvidence:false,stonecrossRatsResolved:false,stonecrossBaitPlaced:false,stonecrossBellRestored:false,stonecrossBellReported:false,stonecrossBellApproach:""};
export const stonecrossDiscoveries={"stonecross-bell-site":{name:"Old bell boathouse located"},"stonecross-bell-advice":{name:"Warning-bell repair advice"},"stonecross-bell-restored":{name:"Stonecross warning bell restored"}};
export const stonecrossClues={"stonecross-bell-advice":{fact:"A fallen beam jams the old boathouse's warning bell; secure the beam and free the bell after resolving the marsh rats.",essential:true,unlocks:"Safe physical warning-bell repair",sources:[{location:"stonecross-inn",methods:["Read Mira's river journal"],outcome:"Establish the boathouse location and repair advice."},{location:"stonecross-boatyard",npc:"stonecross-boatwright",methods:["Inspect Edda's storm-damage report"],outcome:"Independently establish the same repair advice and location."}]}};
export const stonecrossEncounters=[{id:"stonecross-marsh-rats",location:"stonecross-boathouse",resolvedFlag:"stonecrossRatsResolved",
  enemy:{id:"stonecross-marsh-rats",name:"Marsh rat pack",ac:11,hp:18,initiativeModifier:1,attackBonus:2,damageDice:[1,4],damageModifier:0},
  opening:"Large marsh rats burst from beneath the fallen timber and defend their nest. The bell repair must wait until the encounter is resolved.",
  victoryText:"The marsh rat pack scatters into the far reeds and does not return. The beam still jams the bell; the company can now carry out the investigated repair safely.",victoryEffects:[set("stonecrossBellApproach","combat")]}];
export const stonecrossAtlas={id:"stonecross",title:"Stonecross Ferry",root:"ferry",image:"/art/maps/stonecross-local-v1.png",places:stonecrossPlaces,links:stonecrossLinks,
  imageAlt:"Illustrated Stonecross river landing with hut, inn, boatyard, coach court and reedbank. Interactive destinations and discovered routes are marked separately.",
  introduction:"Explore the river hamlet, meet its residents or help with the crossing and warning bell. Public markers are places to visit, not automatic purchases or quest progress.",
  returnHint:"Return to the landing for roads to Rivergate and Willowford. Established carriages board at Stonecross Coach Stop after the connecting road is visited and the ferry mooring repaired.",
  actionIds:["repair-ferry",...stonecrossInteractions.map(action=>action.id)],taskStages:[
    {requires:[flag("stonecrossBellReported")],text:"Jory remembers your help. The warning bell remains restored; return for conversation or continue along the public roads."},
    {requires:[restored],text:"The warning bell is restored. Report back to Jory at the landing."},
    {requires:[calm],text:"The rats are resolved. Use the recorded repair advice at the boathouse; read the inn journal or boatyard report if you have not yet investigated."},
    {requires:[flag("stonecrossBellEvidence")],text:"Repair advice is recorded. Lure the rats away at the reedbank feeding bowl or face the encounter, then repair the bell at the boathouse."},
    {requires:[known],text:"Investigate the bell through the inn journal or boatyard report. The old boathouse is reached through the reedbank."},
    {requires:[],text:"Visit the local residents, repair the ferry mooring at the landing, or ask Jory about the warning bell and local work."},
  ]};
