// An authored settlement package. Artwork is presentation only; these places,
// routes and consequences are the authority and can be reused by any local atlas.
const flag=(name,value=true)=>({path:"flags."+name,equals:value});
const set=(name,value=true)=>({op:"set",path:"flags."+name,value});
export const willowfordPlaces=[
  {id:"village",name:"Willowford Square",x:49,y:45,description:"Footpaths meet at Willowford's village square. The Willow Cup, smithy, orchard, shrine, river landing and coach yard are signposted.",features:[{id:"waypost",label:"village waypost",kind:"scenery",observation:"Six public paths lead to the inn, smithy, orchard, shrine, landing and coach yard. The regional roads lead to Stonecross and Mosswood."}]},
  {id:"willow-inn",name:"The Willow Cup",x:33,y:32,description:"A welcoming timber inn with a kitchen garden and a shaded bench beside its door.",npc:"willow-host",features:[{id:"guest-bench",label:"guest bench",kind:"scenery",observation:"A comfortable bench for conversation; sitting here does not buy a room or restore resources."}]},
  {id:"willow-smithy",name:"Hearthforge Smithy",x:66,y:34,description:"The open forge rings with work on farm tools and carriage fittings.",npc:"willow-smith",features:[{id:"forge",label:"forge",kind:"scenery",observation:"Tongs, an anvil and unfinished iron fittings belong to the smith. Looking does not take or purchase them."}]},
  {id:"willow-orchard",name:"Thorn Orchard",x:23,y:64,description:"Apple trees shade a walled orchard. The irrigation channel is nearly dry despite yesterday's rain.",npc:"orchard",presentations:[{requires:[flag("orchardRestored")],description:"Water runs through Thorn Orchard again. Bessa checks the watered roots beneath the apple trees."}],features:[{id:"irrigation",label:"irrigation channel",kind:"scenery",observation:"The channel is nearly dry. Its upstream flow needs investigating.",presentations:[{requires:[flag("orchardRestored")],observation:"The restored channel carries water evenly between the apple trees."}]}]},
  {id:"willow-shrine",name:"Wayside Shrine",x:65,y:65,description:"A small stone shrine stands beside a shared garden and an old drainage channel.",npc:"willow-tender",features:[{id:"shrine-garden",label:"shared garden",kind:"scenery",observation:"The shrine's garden shares the old overflow channel with the orchard. Its tender can authorise a temporary diversion."}]},
  {id:"willow-landing",name:"Willow Landing",x:86,y:49,description:"A timber landing looks onto the river, with a visible feeder channel running toward the orchard.",npc:"willow-boatkeeper",features:[{id:"feeder",label:"feeder channel",kind:"scenery",observation:"River water enters a channel toward the orchard; the drop in flow must be downstream. No new boat journey is established here."}]},
  {id:"willow-coach",name:"Willowford Coach Yard",x:50,y:14,description:"A stable and carriage yard serve the established public road to Rivergate and Eldervale.",npc:"willow-driver",features:[{id:"coach-board",label:"carriage route board",kind:"scenery",observation:"Carriages connect this yard, Rivergate Market and Eldervale City. First visit the connecting stops; a working Stonecross crossing is required. This introductory public service has no fare."}]},
  {id:"willow-sluice",name:"Orchard Sluice",x:18,y:82,requires:[flag("sluiceKnown")],description:"A low wooden sluice sits beside the orchard's upstream channel. Its grate and overflow lever are within reach.",features:[{id:"sluice-grate",label:"sluice grate",kind:"scenery",observation:"Water piles up behind the grate. Examine the blockage before choosing how to restore the flow.",presentations:[{requires:[flag("orchardRestored")],observation:"Water flows safely again; no further repair is needed."}]},{id:"overflow-lever",label:"overflow lever",kind:"scenery",observation:"The lever diverts water through the shrine's shared garden. Ask its tender's permission before using it."}]},
];
export const willowfordLinks=willowfordPlaces.filter(p=>p.id!=="village"&&p.id!=="willow-sluice").map(p=>["village",p.id]).concat([["willow-orchard","willow-sluice"]]);
export const willowfordAtlas={id:"willowford",title:"Willowford",root:"village",image:"/art/maps/willowford-local-v1.png",places:willowfordPlaces,links:willowfordLinks};
// Public community knowledge is not evidence of visiting a person, nor live
// knowledge of where they are now. Reuse this authoring pattern in each town.
export const willowfordCommunityFacts=[
  "Willowford's public village directory lists Merrin Holt, innkeeper of The Willow Cup; Ada Flint, smith at Hearthforge Smithy; Bessa Thorn, orchard keeper at Thorn Orchard; Sister Fen, tender of Wayside Shrine; Tobin Reed, keeper of Willow Landing; and Cora Bell, driver at Willowford Coach Yard.",
  "Residents can recommend those public places and describe their neighbours' ordinary roles. Usual workplaces are not a claim about someone's current whereabouts.",
  "Village footpaths meet at Willowford Square. Return to the square to reach another public building.",
];
const character=(name,role,location,facts,greeting,conditionalFacts=[])=>({name,role,locations:[location],goals:["Look after Willowford","Welcome travellers without inventing transactions or quests"],voice:"Warm, practical and grounded in village life.",knows:[...willowfordCommunityFacts,...facts],mustNotKnow:["Hidden campaign answers, unestablished people, off-scene current whereabouts, unrevealed quest solutions or unearned rewards"],conversation:{publicFacts:[...willowfordCommunityFacts,...facts],conditionalFacts},greeting});
export const willowfordNpcs={
  orchard:character("Bessa Thorn","Thorn Orchard keeper","willow-orchard",["Willowford sends fruit through Stonecross.","Bessa welcomes help with the orchard's water supply."],"Bessa sets down her basket. “Our trees are thirsty after all that rain. Could you trace the channel, or ask at the river landing? Something has stopped the water.”",[
    {requires:[flag("orchardRestored",false)],fact:"The orchard's channel is nearly dry; investigating its flow can establish an upstream repair route."},
    {requires:[flag("orchardRestored")],fact:"The company restored the orchard's water; Bessa is grateful and no payment or campaign level is awarded."},
    {requires:[flag("orchardMethod","cleared")],fact:"The company cleared the grate and kept the normal channel flowing."},
    {requires:[flag("orchardMethod","bypass")],fact:"With the shrine tender's permission, the company reopened the shared overflow channel."},
  ]),
  "willow-host":character("Merrin Holt","Willow Cup innkeeper","willow-inn",["The Willow Cup is a village inn and meeting place.","The village waypost connects all public places.","Food, room purchases and healing are not implemented here; Merrin can talk but cannot grant them."],"“Come in out of the road dust,” Merrin says. “Bessa's usually in the orchard, and our coach yard is just up the lane. What brings you here?”"),
  "willow-smith":character("Ada Flint","Hearthforge smith","willow-smithy",["Ada repairs farm tools and coach fittings.","Storm debris can choke irrigation grates.","No item sale or free equipment is established."],"Ada rests her hammer. “Road travellers? Have a look, mind the hot iron. I spend more time mending orchard tools than swords.”"),
  "willow-tender":character("Sister Fen","Wayside Shrine tender","willow-shrine",["The shrine tends a garden shared by the village.","Its old overflow channel can carry the orchard's water, but permission must be given through an explicit request.","The shrine offers quiet conversation, not automatic healing or spell restoration."],"Sister Fen brushes soil from her hands. “Welcome. Our garden shares its water with the orchard. We try to leave enough for everyone.”",[{requires:[flag("bypassPermission")],fact:"Sister Fen has authorised using the shared overflow channel to water the orchard."}]),
  "willow-boatkeeper":character("Tobin Reed","Willow Landing keeper","willow-landing",["Tobin maintains the landing, not the Stonecross ferry.","Water enters the orchard's feeder channel here.","Following the feeder's flow can reveal the orchard sluice; no boat travel is offered."],"Tobin points along the feeder channel. “Plenty of water at this end. If Bessa's trees are dry, the trouble's downstream.”"),
  "willow-driver":character("Cora Bell","Willowford coach driver","willow-coach",["Cora drives the public carriage between Willowford, Rivergate Market and Eldervale City.","First visit the connecting places, then use the established carriage route.","The ferry mooring must be repaired for safe carriage service.","No fare is charged in this introductory service."],"Cora checks a harness. “Rivergate and the city, once you've made the road familiar and Jory's crossing is sound. The route board has your options.”"),
};
const portraitAssignments={"willow-host":"merrin","willow-smith":"ada",orchard:"bessa","willow-tender":"fen","willow-boatkeeper":"tobin","willow-driver":"cora"};
for(const [npcId,portraitId] of Object.entries(portraitAssignments)) willowfordNpcs[npcId].portraitId=portraitId;
export const willowfordLocations=Object.fromEntries(willowfordPlaces.map(place=>[place.id,{
  name:place.name,description:place.description,aliases:place.id==="village"?["Willowford","village square"]:[place.name],stage:0,
  map:{x:place.x,y:place.y,w:18,h:14,kind:"court",label:place.name},
  presentations:place.presentations||[],features:[...place.features,...(place.npc?[{id:place.npc,label:willowfordNpcs[place.npc].name,kind:"npc"}]:[])],
  ...(place.id==="village"?{description:place.description+" A few villagers chat by the waypost while farm workers carry baskets across the square."}:{}),
  ...(place.id==="village"?{occupants:["a few villagers chatting beside the waypost","two farm workers carrying baskets across the square"],ambientGreeting:"A villager beside the waypost returns a friendly hello, then gestures toward the signposted village paths."}:{}),
  exits:willowfordLinks.filter(link=>link.includes(place.id)).map(link=>{const to=link.find(id=>id!==place.id);return {to,via:"footpath to "+willowfordPlaces.find(p=>p.id===to).name,...(to==="willow-sluice"?{requires:[flag("sluiceKnown")]}:{})};}),
  entryBeats:place.npc?[{id:place.npc+"-welcome",npc:place.npc,text:willowfordNpcs[place.npc].greeting,...(place.npc==="orchard"?{requires:[flag("orchardRestored",false)]}:{})}]:[],
}]));
const interaction=(id,location,verbs,targets,effects,message,extra={})=>({id,location,modes:["act"],verbs,targets,effects,outcome:{message},...extra});
const discover=[set("sluiceKnown"),{op:"add",path:"discoveries",value:"orchard-sluice"}];
export const willowfordInteractions=[
  ...[["willow-orchard",["channel","irrigation","water","flow"]],["willow-landing",["channel","feeder","water","flow"]]].map(([location,targets])=>interaction("trace-flow-"+location,location,["inspect","examine","investigate","trace","follow","look"],targets,discover,"Tracing the slow flow reveals a footpath from Thorn Orchard to its upstream sluice. The sluice is now marked on the local map. The company stays here.",{repeat:{message:"The orchard sluice is already marked. Reach it by the footpath from Thorn Orchard."}})),
  interaction("diagnose-sluice","willow-sluice",["inspect","examine","investigate","look"],["grate","blockage","sluice"],[set("blockageKnown")],"Storm branches are wedged against the grate. You can clear the debris by hand, or ask Sister Fen at the shrine for permission to use the overflow lever.",{requires:[flag("orchardRestored",false)],repeat:{message:"The blockage is storm debris at the grate. Clear it, or use the overflow after obtaining the shrine tender's permission."}}),
  interaction("permit-overflow","willow-shrine",["ask","request"],["permission","overflow","diversion","bypass"],[set("bypassPermission")],"Sister Fen agrees: “Open the overflow while the orchard needs it. Our shared garden can carry the extra water safely.” Permission is recorded, but the lever has not been moved.",{modes:["act","speak"],requires:[flag("sluiceKnown")],blocked:{message:"First investigate the orchard's water or the feeder channel so the proposed diversion has an established purpose."},repeat:{message:"Sister Fen has already agreed to the orchard's shared overflow."}}),
  ...[
    {id:"clear-orchard-grate",verbs:["clear","remove","unblock"],targets:["debris","branches","grate","blockage"],method:"cleared",requires:[],message:"The company removes the storm branches by hand. Water runs through the normal channel into Thorn Orchard again. Bessa can now be told the good news."},
    {id:"divert-orchard-flow",verbs:["open","turn","use","pull"],targets:["overflow","lever","bypass"],method:"bypass",requires:[flag("bypassPermission")],message:"The company opens the authorised overflow. Water passes through the shared garden channel and reaches Thorn Orchard again. Bessa can now be told the good news."},
  ].map(choice=>interaction(choice.id,"willow-sluice",choice.verbs,choice.targets,[set("orchardRestored"),set("orchardMethod",choice.method),{op:"add",path:"discoveries",value:"orchard-water-restored"}],choice.message,{requires:[flag("blockageKnown"),flag("orchardRestored",false),...choice.requires],blocked:{message:"Examine the sluice blockage first. The overflow also needs Sister Fen's permission. If the water is already restored, no further repair is needed."},repeat:{message:"The orchard's water is already restored; no duplicate consequence or reward is granted."}})),
  interaction("report-orchard-water","willow-orchard",["tell","report","share"],["Bessa","water","repair","news"],[set("orchardReported")],"Bessa checks the flowing water and smiles. “That's a whole season you've helped protect. Come back any time.” The local task is complete. The larger adventure remains exactly where you left it; no campaign levels or invented reward are granted.",{modes:["act","speak"],requires:[flag("orchardRestored")],blocked:{message:"The orchard's water has not been restored yet. Trace its flow to find the cause."},repeat:{message:"Bessa remembers the restored water and welcomes the company back."}}),
];
export const willowfordFlags={sluiceKnown:false,blockageKnown:false,bypassPermission:false,orchardRestored:false,orchardReported:false,orchardMethod:""};
export const willowfordDiscoveries={"orchard-sluice":{name:"Orchard sluice found"},"orchard-water-restored":{name:"Thorn Orchard watered"}};
export const willowfordClues={"orchard-flow":{fact:"Storm branches obstruct the orchard sluice; clearing the grate or using an authorised overflow restores the water.",essential:true,unlocks:"Two optional solutions to Thorn Orchard's water problem",sources:[{location:"willow-orchard",methods:["Trace the irrigation channel"],outcome:"Reveal the footpath to the sluice."},{location:"willow-landing",npc:"willow-boatkeeper",methods:["Investigate the feeder channel"],outcome:"Reveal the same sluice via an independent source."}]}};
