const packageFor = (theme) => Object.freeze(theme);

export const THEME_PACKAGE_VERSION = 1;

export const UNIVERSE_THEMES = Object.freeze({
  hearthbound: packageFor({
    id: "hearthbound",
    displayName: "Hearthbound",
    wordmark: "Hearthbound",
    icon: "shield",
    art: "/art/universes/hearthbound.webp",
    artAlt: "A brass lantern illuminating an old map and compass beside a rain-dark mountain road.",
    genre: "High fantasy",
    availability: "playable",
    tagline: "Old roads, warm lanterns, and family legends.",
    description: "A high-fantasy world of buried kingdoms, hand-drawn maps, and adventures shared around the hearth.",
    palette: { ink:"#12100e", panel:"#1b1814", panelRaised:"#2b2318", accent:"#caa45d", accentBright:"#f0cb7a", text:"#f1eadb", muted:"#aaa093", line:"#4b3d2a", danger:"#a34b42" },
    typography: { heading:'Georgia, "Times New Roman", serif', body:'Inter, Aptos, system-ui, sans-serif' },
    texture: "Vellum, leather, dark wood, and engraved bronze",
    motifs: ["Lanterns", "Compasses", "Heraldry", "Hand-drawn maps"],
    mapTreatment: "Parchment atlas with engraved routes and warm-gold discoveries",
    sceneArtStyle: "Painterly high fantasy, warm lantern light, weathered natural materials, no modern objects",
    narrationMood: "Welcoming fireside storyteller with grounded wonder",
    audioMood: "Low hearth, distant rain, bowed strings, and restrained hand percussion",
    terms: { library:"Game library", campaign:"Campaign", campaigns:"Campaigns", content:"Adventure", contents:"Adventures", character:"Character", characters:"Characters", characterSheet:"Character sheet", map:"Known map", party:"Party", parties:"Parties", journal:"Campaign journal", play:"Play" },
  }),
  supernatural: packageFor({
    id: "supernatural",
    displayName: "Hunters",
    wordmark: "Hunters",
    icon: "cross",
    art: "/art/universes/supernatural.webp",
    artAlt: "A worn road atlas, warding charm, cassette recorder, and case photograph on a motel table at night.",
    genre: "Modern supernatural",
    availability: "planned",
    tagline: "Every town has a story it does not tell after dark.",
    description: "Roadside cases, dangerous folklore, and a continuing season mystery recorded in a hard-won hunter's journal.",
    palette: { ink:"#101313", panel:"#191c1b", panelRaised:"#272b29", accent:"#8fafbc", accentBright:"#c7dfe7", text:"#eee9dc", muted:"#aaa79d", line:"#40545a", danger:"#b23b32" },
    typography: { heading:'Rockwell, "Roboto Slab", Georgia, serif', body:'"Arial Narrow", Inter, Aptos, sans-serif' },
    texture: "Worn motel paper, case files, scratched metal, and cassette static",
    motifs: ["Road atlases", "Warding symbols", "Evidence photos", "Cassette noise"],
    mapTreatment: "Folded road atlas annotated with warning red, sightings, and safehouses",
    sceneArtStyle: "Cinematic roadside supernatural thriller, available light, evidence-photo grain, warning-red annotations",
    narrationMood: "Tense road-story pacing with practical details and slowly accumulating dread",
    audioMood: "Tyre noise, motel neon hum, radio static, and sparse electric guitar",
    terms: { library:"Game library", campaign:"Season", campaigns:"Seasons", content:"Episode", contents:"Episodes", character:"Hunter", characters:"Hunters", characterSheet:"Hunter journal", map:"Case map", party:"Cast", parties:"Casts", journal:"Journal", play:"Play episode" },
  }),
  mystery: packageFor({
    id: "mystery",
    displayName: "Unmasked",
    wordmark: "Unmasked",
    icon: "magnifier",
    art: "/art/universes/mystery.webp",
    artAlt: "A midnight-blue evidence desk with case files, fingerprints, photographs, red string, and a brass magnifying glass.",
    genre: "Murder mystery",
    availability: "planned",
    tagline: "Every alibi leaves a mark.",
    description: "Closed circles, contested timelines, and evidence that rewards careful investigators rather than lucky guesses.",
    palette: { ink:"#0c1420", panel:"#131e2c", panelRaised:"#1c2b3c", accent:"#b99a58", accentBright:"#ead7a2", text:"#f4efe4", muted:"#aab2ba", line:"#35475a", danger:"#a83d3d" },
    typography: { heading:'"Baskerville", Georgia, serif', body:'"Courier New", Inter, monospace' },
    texture: "Case folders, typewriter paper, photographic stock, and sealing wax",
    motifs: ["Red string", "Fingerprints", "Official seals", "Annotated documents"],
    mapTreatment: "Evidence board linking suspects, places, testimony, and a verified timeline",
    sceneArtStyle: "Editorial crime photography, midnight shadows, ivory documents, brass details, no supernatural imagery",
    narrationMood: "Precise, observant, and withholding only what the investigators have not established",
    audioMood: "Clockwork, quiet rooms, camera shutters, and spare piano",
    terms: { library:"Game library", campaign:"Casebook", campaigns:"Casebooks", content:"Case", contents:"Cases", character:"Investigator", characters:"Investigators", characterSheet:"Investigator file", map:"Evidence board", party:"Investigation team", parties:"Investigation teams", journal:"Timeline", play:"Open case" },
  }),
  gothic: packageFor({
    id: "gothic",
    displayName: "Forsaken",
    wordmark: "Forsaken",
    icon: "pentacle-image",
    art: "/art/universes/gothic.webp",
    artAlt: "A tarnished family crest, candle, and sealed letter before a moonlit gothic window.",
    genre: "Gothic horror",
    availability: "planned",
    tagline: "The house remembers every name.",
    description: "A candlelit chronicle of inherited guilt, haunted estates, and choices that leave permanent scars.",
    palette: { ink:"#100b0c", panel:"#1c1214", panelRaised:"#2b191d", accent:"#c45f69", accentBright:"#ef9ca4", text:"#f0e7dc", muted:"#a89a98", line:"#57383d", danger:"#772b31" },
    typography: { heading:'Garamond, "Times New Roman", serif', body:'Georgia, Aptos, serif' },
    texture: "Cracked plaster, velvet, old paper, and wrought iron",
    motifs: ["Family crests", "Cathedral tracery", "Wax seals", "Moonlight"],
    mapTreatment: "Tarnished estate plan and regional chart revealed by candlelight",
    sceneArtStyle: "Romantic gothic painting, moonlit architecture, candle ivory, oxblood velvet, deep shadow",
    narrationMood: "Intimate, elegiac, and ominous without obscuring actionable detail",
    audioMood: "Wind through stone, distant bells, floorboards, and low choral texture",
    terms: { library:"Game library", campaign:"Chronicle", campaigns:"Chronicles", content:"Chapter", contents:"Chapters", character:"Character", characters:"Characters", characterSheet:"Character record", map:"Estate map", party:"Household", parties:"Households", journal:"Family chronicle", play:"Enter chronicle" },
  }),
  cosmic: packageFor({
    id: "cosmic",
    displayName: "Hysteria",
    wordmark: "Hysteria",
    icon: "cthulhu-bust",
    art: "/art/universes/cosmic.webp",
    artAlt: "A teal-lit scientific worktable with microscope, degraded film, specimen drawings, and an impossible geometric shadow.",
    genre: "Cosmic horror",
    availability: "planned",
    tagline: "Some conclusions should not be reached.",
    description: "Investigations into degraded records, impossible patterns, and knowledge that changes the people who uncover it.",
    palette: { ink:"#080d0d", panel:"#101919", panelRaised:"#172524", accent:"#4d9b8e", accentBright:"#91d2c4", text:"#e7e5d8", muted:"#92a39d", line:"#28433e", danger:"#82474b" },
    typography: { heading:'"Palatino Linotype", Georgia, serif', body:'"Courier New", Consolas, monospace' },
    texture: "Scientific notes, degraded film, redactions, and impossible geometry",
    motifs: ["Specimen diagrams", "Redactions", "Geometric distortion", "Forbidden texts"],
    mapTreatment: "Evidence map distorted by unreliable scale, redactions, and accumulating stress",
    sceneArtStyle: "Archival scientific photography, sickly teal chemistry, degraded emulsion, unsettling impossible scale",
    narrationMood: "Clinical observation gradually destabilised by precise contradictions",
    audioMood: "Tape hiss, sub-bass resonance, fluorescent buzz, and tones that almost resolve",
    terms: { library:"Game library", campaign:"Investigation", campaigns:"Investigations", content:"Dossier", contents:"Dossiers", character:"Investigator", characters:"Investigators", characterSheet:"Investigator record", map:"Evidence map", party:"Field team", parties:"Field teams", journal:"Research log", play:"Continue investigation" },
  }),
  espionage: packageFor({
    id: "espionage",
    displayName: "Classified",
    wordmark: "Classified",
    icon: "dossier",
    art: "/art/universes/espionage.webp",
    artAlt: "A secure operations desk with dossiers, microfilm, cipher wheel, surveillance photographs, and a terminal-green world grid.",
    genre: "Espionage",
    availability: "planned",
    tagline: "Trust is a clearance level.",
    description: "Covert operations, compromised contacts, and intelligence assembled under pressure across a living world grid.",
    palette: { ink:"#0b0e0d", panel:"#111715", panelRaised:"#1b2420", accent:"#65a976", accentBright:"#a9d99f", text:"#e9e5d8", muted:"#9ba49d", line:"#33483b", danger:"#b26735" },
    typography: { heading:'"Arial Narrow", Inter, sans-serif', body:'Consolas, "Courier New", monospace' },
    texture: "Secure terminals, microfilm, dossier cream, and stamped folders",
    motifs: ["Clearance stamps", "Ciphers", "Surveillance", "World grids"],
    mapTreatment: "Dark operations grid with routes, assets, threats, and clearance-coded intel",
    sceneArtStyle: "Cold-war dossier collage, surveillance optics, graphite, terminal green, amber status lights",
    narrationMood: "Concise operational briefing sharpened by uncertainty and conflicting intelligence",
    audioMood: "Encrypted radio, teletype, ventilation hum, and restrained analogue pulse",
    terms: { library:"Game library", campaign:"Directorate", campaigns:"Directorates", content:"Operation", contents:"Operations", character:"Agent", characters:"Agents", characterSheet:"Agent dossier", map:"Intel map", party:"Cell", parties:"Cells", journal:"Contacts", play:"Begin operation" },
  }),
});

export const UNIVERSE_IDS = Object.freeze(Object.keys(UNIVERSE_THEMES));

export function universeTheme(id) {
  return UNIVERSE_THEMES[id] || UNIVERSE_THEMES.hearthbound;
}

export function universeIdForWorld(world) {
  const explicit = String(world?.universeId || "").toLowerCase();
  if (UNIVERSE_THEMES[explicit]) return explicit;
  const prefix = String(world?.id || "").toLowerCase().split(/[:/]/, 1)[0];
  return UNIVERSE_THEMES[prefix] ? prefix : "hearthbound";
}
